<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An introductory resource for working with geographic data in Python">

<title>Geocomputation with Python - 5&nbsp; Raster-vector interactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-reproj.html" rel="next">
<link href="./04-geometry-operations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-raster-vector.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Raster-vector interactions</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Geocomputation with Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/geocompx/geocompy/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Geographic data in Python</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-attribute-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Attribute data operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-spatial-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatial data operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-geometry-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Geometry operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-raster-vector.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Raster-vector interactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-reproj.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reprojecting geographic data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-read-write-plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Geographic data I/O</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Making maps with Python</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
  <h2 class="anchored">Note: The book is under construction 🏗</h2>
  <ul>
    <li><a href="https://github.com/geocompr/py/issues" class="nav-link active" data-scroll-target="https\://github.com/geocompr/py/issues">Open an issue ❔</a></li>
    <li><a href="https://discord.gg/PMztXYgNxp" class="nav-link" data-scroll-target="https\://discord.gg/PMztXYgNxp">Chat on Discord 📣</a></li>
  </ul>
  <hr>
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#sec-raster-cropping" id="toc-sec-raster-cropping" class="nav-link" data-scroll-target="#sec-raster-cropping"><span class="header-section-number">5.2</span> Raster masking and cropping</a></li>
  <li><a href="#sec-raster-extraction" id="toc-sec-raster-extraction" class="nav-link" data-scroll-target="#sec-raster-extraction"><span class="header-section-number">5.3</span> Raster extraction</a>
  <ul>
  <li><a href="#sec-extraction-to-points" id="toc-sec-extraction-to-points" class="nav-link" data-scroll-target="#sec-extraction-to-points"><span class="header-section-number">5.3.1</span> Extraction to points</a></li>
  <li><a href="#sec-extraction-to-lines" id="toc-sec-extraction-to-lines" class="nav-link" data-scroll-target="#sec-extraction-to-lines"><span class="header-section-number">5.3.2</span> Extraction to lines</a></li>
  <li><a href="#sec-extraction-to-polygons" id="toc-sec-extraction-to-polygons" class="nav-link" data-scroll-target="#sec-extraction-to-polygons"><span class="header-section-number">5.3.3</span> Extraction to polygons</a></li>
  </ul></li>
  <li><a href="#sec-rasterization" id="toc-sec-rasterization" class="nav-link" data-scroll-target="#sec-rasterization"><span class="header-section-number">5.4</span> Rasterization</a>
  <ul>
  <li><a href="#sec-rasterizing-points" id="toc-sec-rasterizing-points" class="nav-link" data-scroll-target="#sec-rasterizing-points"><span class="header-section-number">5.4.1</span> Rasterizing points</a></li>
  <li><a href="#rasterizing-lines-and-polygons" id="toc-rasterizing-lines-and-polygons" class="nav-link" data-scroll-target="#rasterizing-lines-and-polygons"><span class="header-section-number">5.4.2</span> Rasterizing lines and polygons</a></li>
  </ul></li>
  <li><a href="#sec-spatial-vectorization" id="toc-sec-spatial-vectorization" class="nav-link" data-scroll-target="#sec-spatial-vectorization"><span class="header-section-number">5.5</span> Spatial vectorization</a>
  <ul>
  <li><a href="#sec-raster-to-polygons" id="toc-sec-raster-to-polygons" class="nav-link" data-scroll-target="#sec-raster-to-polygons"><span class="header-section-number">5.5.1</span> Raster to polygons</a></li>
  <li><a href="#sec-raster-to-points" id="toc-sec-raster-to-points" class="nav-link" data-scroll-target="#sec-raster-to-points"><span class="header-section-number">5.5.2</span> Raster to points</a></li>
  <li><a href="#sec-raster-to-contours" id="toc-sec-raster-to-contours" class="nav-link" data-scroll-target="#sec-raster-to-contours"><span class="header-section-number">5.5.3</span> Raster to contours</a></li>
  </ul></li>
  <li><a href="#sec-distance-to-nearest-geometry" id="toc-sec-distance-to-nearest-geometry" class="nav-link" data-scroll-target="#sec-distance-to-nearest-geometry"><span class="header-section-number">5.6</span> Distance to nearest geometry</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">5.7</span> Exercises</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/geocompx/geocompy/edit/main/05-raster-vector.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-raster-vector" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Raster-vector interactions</span></span></h1>
</div>

<!--
-->


<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="prerequisites" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="prerequisites">Prerequisites</h2>
<p>This chapter requires importing the following packages: <!--jn:two packages are commented out -- should these lines be removed?--> <!--md: yes, done--></p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> shapely</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio.mask</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterstats</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio.plot</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio.features</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It also relies on the following data files:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>src_srtm <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'data/srtm.tif'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>src_nlcd <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'data/nlcd.tif'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>src_grain <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/grain.tif'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>src_elev <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/elev.tif'</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>src_dem <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'data/dem.tif'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>zion <span class="op">=</span> gpd.read_file(<span class="st">'data/zion.gpkg'</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>zion_points <span class="op">=</span> gpd.read_file(<span class="st">'data/zion_points.gpkg'</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>cycle_hire_osm <span class="op">=</span> gpd.read_file(<span class="st">'data/cycle_hire_osm.gpkg'</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>us_states <span class="op">=</span> gpd.read_file(<span class="st">'data/us_states.gpkg'</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>nz <span class="op">=</span> gpd.read_file(<span class="st">'data/nz.gpkg'</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>src_nz_elev <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'data/nz_elev.tif'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.1</span> Introduction</h2>
<p>This chapter focuses on interactions between raster and vector geographic data models, both introduced in <a href="01-spatial-data.html"><span>Chapter&nbsp;1</span></a>. It includes four main techniques:</p>
<ul>
<li>Raster cropping and masking using vector objects (<a href="#sec-raster-cropping"><span>Section&nbsp;5.2</span></a>)</li>
<li>Extracting raster values using different types of vector data (Section <a href="#sec-raster-extraction"><span>Section&nbsp;5.3</span></a>)</li>
<li>Raster-vector conversion (<a href="#sec-rasterization"><span>Section&nbsp;5.4</span></a> and <a href="#sec-spatial-vectorization"><span>Section&nbsp;5.5</span></a>)</li>
</ul>
<p>These concepts are demonstrated using data from in previous chapters, to understand their potential real-world applications.</p>
</section>
<section id="sec-raster-cropping" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-raster-cropping"><span class="header-section-number">5.2</span> Raster masking and cropping</h2>
<p>Many geographic data projects involve integrating data from many different sources, such as remote sensing images (rasters) and administrative boundaries (vectors). Often the extent of input raster datasets is larger than the area of interest. In this case raster <em>masking</em>, <em>cropping</em>, or both, are useful for unifying the spatial extent of input data (<a href="#fig-raster-crop">Figure&nbsp;<span>5.2</span></a> (b) and (c), and the following two examples, illustrate the difference between masking and cropping). Both operations reduce object memory use and associated computational resources for subsequent analysis steps, and may be a necessary preprocessing step before creating attractive maps involving raster data.</p>
<p>We will use two layers to illustrate raster cropping:</p>
<ul>
<li>The <code>srtm.tif</code> raster representing elevation, in meters above sea level, in south-western Utah: a <strong>rasterio</strong> file connection named <code>src_srtm</code> (see <a href="#fig-raster-crop">Figure&nbsp;<span>5.2</span></a> (a))</li>
<li>The <code>zion.gpkg</code> vector layer representing the Zion National Park boundaries (a <code>GeoDataFrame</code> named <code>zion</code>)</li>
</ul>
<p>Both target and cropping objects must have the same projection. Since it is easier and more precise to reproject vector layers, compared to rasters, we use the following expression to reproject (<a href="06-reproj.html#sec-reprojecting-vector-geometries"><span>Section&nbsp;6.7</span></a>) the vector layer <code>zion</code> into the CRS of the raster <code>src_srtm</code>. <!-- jn: maybe reference to the CRS section/chapter --> <!-- md: done --></p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>zion <span class="op">=</span> zion.to_crs(src_srtm.crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To mask the image, i.e., convert all pixels which do not intersect with the <code>zion</code> polygon to “No Data”, we use the <a href="https://rasterio.readthedocs.io/en/stable/api/rasterio.mask.html#rasterio.mask.mask"><code>rasterio.mask.mask</code></a> function.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>out_image_mask, out_transform_mask <span class="op">=</span> rasterio.mask.mask(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    src_srtm, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    zion.geometry, </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    crop<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    nodata<span class="op">=</span><span class="dv">9999</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that we need to choose and specify a “No Data” value, within the valid range according to the data type. Since <code>srtm.tif</code> is of type <code>uint16</code> (how can we check?), we choose <code>9999</code> (a positive integer that is guaranteed not to occur in the raster). Also note that <strong>rasterio</strong> does not directly support <strong>geopandas</strong> data structures, so we need to pass a “collection” of <strong>shapely</strong> geometries: a <code>GeoSeries</code> (see below) or a <code>list</code> of <strong>shapely</strong> geometries (see next example) both work. <!-- jn: (see below) or (see above) --> The output consists of two objects. The first one is the <code>out_image</code> array with the masked values.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>out_image_mask</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>array([[[9999, 9999, 9999, ..., 9999, 9999, 9999],
        [9999, 9999, 9999, ..., 9999, 9999, 9999],
        [9999, 9999, 9999, ..., 9999, 9999, 9999],
        ...,
        [9999, 9999, 9999, ..., 9999, 9999, 9999],
        [9999, 9999, 9999, ..., 9999, 9999, 9999],
        [9999, 9999, 9999, ..., 9999, 9999, 9999]]], dtype=uint16)</code></pre>
</div>
</div>
<p>The second one is a new transformation matrix <code>out_transform</code>.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>out_transform_mask</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>Affine(0.0008333333332777796, 0.0, -113.23958321278403,
       0.0, -0.0008333333332777843, 37.512916763165805)</code></pre>
</div>
</div>
<p>Note that masking (without cropping!) does not modify the raster extent. Therefore, the new transform is identical to the original (<code>src_srtm.transform</code>).</p>
<p>Unfortunately, the <code>out_image</code> and <code>out_transform</code> objects do not contain any information indicating that <code>9999</code> represents “No Data”. To associate the information with the raster, we must write it to file along with the corresponding metadata. For example, to write the masked raster to file, we first need to modify the “No Data” setting in the metadata.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dst_kwargs <span class="op">=</span> src_srtm.meta</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dst_kwargs.update(nodata<span class="op">=</span><span class="dv">9999</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>dst_kwargs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': 9999,
 'width': 465,
 'height': 457,
 'count': 1,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(0.0008333333332777796, 0.0, -113.23958321278403,
        0.0, -0.0008333333332777843, 37.512916763165805)}</code></pre>
</div>
</div>
<p>Then we can write the masked raster to file with the updated metadata object.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>new_dataset <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/srtm_masked.tif'</span>, <span class="st">'w'</span>, <span class="op">**</span>dst_kwargs)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>new_dataset.write(out_image_mask)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>new_dataset.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can re-import the raster and check that the “No Data” value is correctly set.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>src_srtm_mask <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/srtm_masked.tif'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>.meta</code> property contains the <code>nodata</code> entry. Now, any relevant operation (such as plotting) will take “No Data” into account.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>src_srtm_mask.meta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': 9999.0,
 'width': 465,
 'height': 457,
 'count': 1,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(0.0008333333332777796, 0.0, -113.23958321278403,
        0.0, -0.0008333333332777843, 37.512916763165805)}</code></pre>
</div>
</div>
<p>The related operation, cropping, reduces the raster extent to the extent of the vector layer:</p>
<ul>
<li>To just crop, <em>without</em> masking, we can derive the bounding box polygon of the vector layer, and then crop using that polygon, also combined with <code>crop=True</code> (<a href="#fig-raster-crop">Figure&nbsp;<span>5.2</span></a> (c))</li>
<li>To crop <em>and</em> mask, we can use <code>rasterio.mask.mask</code>, same as above for masking, just setting <code>crop=True</code> instead of the default <code>crop=False</code> (<a href="#fig-raster-crop">Figure&nbsp;<span>5.2</span></a> (d))</li>
</ul>
<p>For the example of cropping only, the extent polygon of <code>zion</code> can be obtained as a <code>shapely</code> geometry object using the <code>.unary_union.envelope</code> property(<a href="#fig-zion-bbox">Figure&nbsp;<span>5.1</span></a>).</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>bb <span class="op">=</span> zion.unary_union.envelope</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>bb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div id="fig-zion-bbox" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-zion-bbox-output-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.1: Bounding box <code>'Polygon'</code> geometry of the <code>zion</code> layer</figcaption>
</figure>
</div>
</div>
</div>
<p>The extent can now be used for masking. Here, we are also using the <code>all_touched=True</code> option so that pixels partially overlapping with the extent are also included in the output.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>out_image_crop, out_transform_crop <span class="op">=</span> rasterio.mask.mask(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    src_srtm, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    [bb], </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    crop<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    all_touched<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    nodata<span class="op">=</span><span class="dv">9999</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- jn: why [bb] and not bb? -->
<p>Finally, we can perform crop and mask operations, using <code>rasterio.mask.mask</code> with <code>crop=True</code>. When writing to file, it is now crucial to update the transform and dimensions, since they were modified as a result of cropping. Also note that <code>out_image_mask_crop</code> is a three-dimensional array (even tough it has one band in this case), so the number of rows and columns are in <code>.shape[1]</code> and <code>.shape[2]</code> (rather than <code>.shape[0]</code> and <code>.shape[1]</code>), respectively. <!-- jn: why? --> <!-- jn: maybe split the code below into two chunks and describe them separately...? --></p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>out_image_mask_crop, out_transform_mask_crop <span class="op">=</span> rasterio.mask.mask(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    src_srtm, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    zion.geometry, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    crop<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    nodata<span class="op">=</span><span class="dv">9999</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>dst_kwargs <span class="op">=</span> src_srtm.meta</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>dst_kwargs.update({</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'nodata'</span>: <span class="dv">9999</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'transform'</span>: out_transform_mask_crop,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'width'</span>: out_image_mask_crop.shape[<span class="dv">2</span>],</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'height'</span>: out_image_mask_crop.shape[<span class="dv">1</span>]</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>new_dataset <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/srtm_masked_cropped.tif'</span>, <span class="st">'w'</span>, <span class="op">**</span>dst_kwargs)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>new_dataset.write(out_image_mask_crop)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>new_dataset.close()</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>src_srtm_mask_crop <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/srtm_masked_cropped.tif'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>out_image_mask_crop.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>(1, 436, 439)</code></pre>
</div>
</div>
<p><a href="#fig-raster-crop">Figure&nbsp;<span>5.2</span></a> shows the original raster, and the all of the masked and cropped results.</p>
<div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Original</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">3.5</span>, <span class="fl">3.5</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_srtm, ax<span class="op">=</span>ax)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>zion.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Masked</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">3.5</span>, <span class="fl">3.5</span>))</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_srtm_mask, ax<span class="op">=</span>ax)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>zion.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Cropped</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">3.5</span>, <span class="fl">3.5</span>))</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(out_image_crop, transform<span class="op">=</span>out_transform_crop, ax<span class="op">=</span>ax)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>zion.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Masked+Cropped</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">3.5</span>, <span class="fl">3.5</span>))</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_srtm_mask_crop, ax<span class="op">=</span>ax)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>zion.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-raster-crop" class="cell quarto-layout-panel" data-execution_count="16">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-raster-crop-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-crop-output-1.png" class="img-fluid figure-img" data-ref-parent="fig-raster-crop" width="276"></p>
<figcaption class="figure-caption">(a) Original</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-raster-crop-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-crop-output-2.png" class="img-fluid figure-img" data-ref-parent="fig-raster-crop" width="276"></p>
<figcaption class="figure-caption">(b) Masked</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-raster-crop-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-crop-output-3.png" class="img-fluid figure-img" data-ref-parent="fig-raster-crop" width="277"></p>
<figcaption class="figure-caption">(c) Cropped</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-raster-crop-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-crop-output-4.png" class="img-fluid figure-img" data-ref-parent="fig-raster-crop" width="277"></p>
<figcaption class="figure-caption">(d) Masked+Cropped</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;5.2: Raster masking and cropping</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="sec-raster-extraction" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-raster-extraction"><span class="header-section-number">5.3</span> Raster extraction</h2>
<p>Raster extraction is the process of identifying and returning the values associated with a ‘target’ raster at specific locations, based on a (typically vector) geographic ‘selector’ object. The reverse of raster extraction—assigning raster cell values based on vector objects—is rasterization, described in <a href="#sec-rasterization"><span>Section&nbsp;5.4</span></a>.</p>
<p>In the following examples, we use a package called <strong>rasterstats</strong>, which is specifically aimed at extracting raster values:</p>
<ul>
<li>To <em>points</em> (<a href="#sec-extraction-to-points"><span>Section&nbsp;5.3.1</span></a>) or to <em>lines</em> (<a href="#sec-extraction-to-lines"><span>Section&nbsp;5.3.2</span></a>), via the <code>rasterstats.point_query</code> function</li>
<li>To <em>polygons</em> (<a href="#sec-extraction-to-polygons"><span>Section&nbsp;5.3.3</span></a>), via the <code>rasterstats.zonal_stats</code> function</li>
</ul>
<section id="sec-extraction-to-points" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="sec-extraction-to-points"><span class="header-section-number">5.3.1</span> Extraction to points</h3>
<p>The simplest type of raster extraction is getting the values of raster cells at specific points. To demonstrate extraction to points, we will use <code>zion_points</code>, which contains a sample of 30 locations within the Zion National Park (<a href="#fig-zion-points">Figure&nbsp;<span>5.3</span></a>).</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_srtm, ax<span class="op">=</span>ax)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>zion_points.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-zion-points" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-zion-points-output-1.png" width="366" height="411" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.3: 30 point locations within the Zion National Park, with elevation in the background</figcaption>
</figure>
</div>
</div>
</div>
<p>The following expression extracts elevation values from <code>srtm.tif</code> according to <code>zion_points</code>, using <code>rasterstats.point_query</code>.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> rasterstats.point_query(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    zion_points, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    src_srtm.read(<span class="dv">1</span>), </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    nodata <span class="op">=</span> src_srtm.nodata, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    affine <span class="op">=</span> src_srtm.transform,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    interpolate<span class="op">=</span><span class="st">'nearest'</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- jn: explain the above arguments -->
<p>The resulting object is a <code>list</code> of raster values, corresponding to <code>zion_points</code>. For example, here are the elevations of the first five points.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>result[:<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>[1802, 2433, 1886, 1370, 1452]</code></pre>
</div>
</div>
<p>To get a <code>GeoDataFrame</code> with the original points geometries (and other attributes, if any), as well as the extracted raster values, we can assign the extraction result into a new column.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>zion_points[<span class="st">'elev'</span>] <span class="op">=</span> result</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>zion_points</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">elev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>POINT (-112.91587 37.20013)</td>
<td>1802</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>POINT (-113.09369 37.39263)</td>
<td>2433</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>POINT (-113.02462 37.33466)</td>
<td>1886</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">27</td>
<td>POINT (-113.03655 37.23446)</td>
<td>1372</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">28</td>
<td>POINT (-113.13933 37.39004)</td>
<td>1905</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">29</td>
<td>POINT (-113.09677 37.24237)</td>
<td>1574</td>
</tr>
</tbody>
</table>

<p>30 rows × 2 columns</p>
</div>
</div>
</div>
<!-- jn: what with multilayer raster? -->
</section>
<section id="sec-extraction-to-lines" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="sec-extraction-to-lines"><span class="header-section-number">5.3.2</span> Extraction to lines</h3>
<p>Raster extraction is also applicable with line selectors. The typical line extraction algorithm is to extract one value for each raster cell touched by a line. However, this particular approach is not recommended to obtain values along the transects, as it is hard to get the correct distance between each pair of extracted raster values.</p>
<p>For line extraction, a better approach is to split the line into many points (at equal distances along the line) and then extract the values for these points using the “extraction to points” technique (<a href="#sec-extraction-to-points"><span>Section&nbsp;5.3.1</span></a>). To demonstrate this, the code below creates (see <a href="01-spatial-data.html#sec-vector-data"><span>Section&nbsp;1.2</span></a> for recap) <code>zion_transect</code>, a straight line going from northwest to southeast of the Zion National Park.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>coords <span class="op">=</span> [[<span class="op">-</span><span class="fl">113.2</span>, <span class="fl">37.45</span>], [<span class="op">-</span><span class="fl">112.9</span>, <span class="fl">37.2</span>]]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>zion_transect <span class="op">=</span> shapely.LineString(coords)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zion_transect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LINESTRING (-113.2 37.45, -112.9 37.2)</code></pre>
</div>
</div>
<p>The utility of extracting heights from a linear selector is illustrated by imagining that you are planning a hike. The method demonstrated below provides an ‘elevation profile’ of the route (the line does not need to be straight), useful for estimating how long it will take due to long climbs.</p>
<p>First, we need to create a layer consisting of points along our line (<code>zion_transect</code>), at specified intervals (e.g., <code>250</code>). To do that, we need to transform the line into a projected CRS (so that we work with true distances, in <span class="math inline">\(m\)</span>), such as UTM. This requires going through a <code>GeoSeries</code>, as <strong>shapely</strong> geometries have no CRS definition nor concept of reprojection (see <a href="01-spatial-data.html#sec-vector-layer-from-scratch"><span>Section&nbsp;1.2.6</span></a>).</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>zion_transect_utm <span class="op">=</span> gpd.GeoSeries(zion_transect, crs<span class="op">=</span><span class="dv">4326</span>).to_crs(<span class="dv">32612</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>zion_transect_utm <span class="op">=</span> zion_transect_utm.iloc[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The printout of the new geometry shows this is still a straight line between two points, only with coordinates in a projected CRS.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zion_transect_utm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LINESTRING (305399.67208180577 4147066.650206682, 331380.8917453843 4118750.0947884847)</code></pre>
</div>
</div>
<p>Next, we need to calculate the distances, along the line, where points are going to be generated, using <a href="https://numpy.org/doc/stable/reference/generated/numpy.arange.html"><code>np.arange</code></a>. This is a numeric sequence starting at <code>0</code>, going up to line <code>.length</code>, in steps of <code>250</code> (<span class="math inline">\(m\)</span>).</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>distances <span class="op">=</span> np.arange(<span class="dv">0</span>, zion_transect_utm.length, <span class="dv">250</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>distances[:<span class="dv">7</span>]  <span class="co">## First 7 distance cutoff points</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>array([   0.,  250.,  500.,  750., 1000., 1250., 1500.])</code></pre>
</div>
</div>
<p>The distances cutoffs are used to sample (“interpolate”) points along the line. The <strong>shapely</strong> <a href="https://shapely.readthedocs.io/en/stable/manual.html#object.interpolate"><code>.interpolate</code></a> method is used to generate the points, which then are reprojected back to the geographic CRS of the raster (EPSG:<code>4326</code>).</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt <span class="op">=</span> [zion_transect_utm.interpolate(distance) <span class="cf">for</span> distance <span class="kw">in</span> distances]</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt <span class="op">=</span> gpd.GeoSeries(zion_transect_pnt, crs<span class="op">=</span><span class="dv">32612</span>).to_crs(src_srtm.crs)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>0      POINT (-113.20000 37.45000)
1      POINT (-113.19804 37.44838)
2      POINT (-113.19608 37.44675)
                  ...             
151    POINT (-112.90529 37.20443)
152    POINT (-112.90334 37.20280)
153    POINT (-112.90140 37.20117)
Length: 154, dtype: geometry</code></pre>
</div>
</div>
<p>Finally, we extract the elevation values for each point in our transect and combine the information with <code>zion_transect_pnt</code> (after “promoting” it to a <code>GeoDataFrame</code>, to accommodate extra attributes), using the point extraction method shown earlier (<a href="#sec-extraction-to-points"><span>Section&nbsp;5.3.1</span></a>). We also attach the respective distance cutoff points <code>distances</code>.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> rasterstats.point_query(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    zion_transect_pnt, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    src_srtm.read(<span class="dv">1</span>), </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    nodata <span class="op">=</span> src_srtm.nodata, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    affine <span class="op">=</span> src_srtm.transform,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    interpolate<span class="op">=</span><span class="st">'nearest'</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt <span class="op">=</span> gpd.GeoDataFrame(geometry<span class="op">=</span>zion_transect_pnt)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt[<span class="st">'dist'</span>] <span class="op">=</span> distances</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt[<span class="st">'elev'</span>] <span class="op">=</span> result</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">dist</th>
<th data-quarto-table-cell-role="th">elev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>POINT (-113.20000 37.45000)</td>
<td>0.0</td>
<td>2001</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>POINT (-113.19804 37.44838)</td>
<td>250.0</td>
<td>2037</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>POINT (-113.19608 37.44675)</td>
<td>500.0</td>
<td>1949</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">151</td>
<td>POINT (-112.90529 37.20443)</td>
<td>37750.0</td>
<td>1837</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">152</td>
<td>POINT (-112.90334 37.20280)</td>
<td>38000.0</td>
<td>1841</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">153</td>
<td>POINT (-112.90140 37.20117)</td>
<td>38250.0</td>
<td>1819</td>
</tr>
</tbody>
</table>

<p>154 rows × 3 columns</p>
</div>
</div>
</div>
<p>The information in <code>zion_transect_pnt</code>, namely the <code>'dist'</code> and <code>'elev'</code> attributes, can now be used to draw an elevation profile, as illustrated in <a href="#fig-zion-transect">Figure&nbsp;<span>5.4</span></a>.</p>
<div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Raster and a line transect</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_srtm, ax<span class="op">=</span>ax)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>gpd.GeoSeries(zion_transect).plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>zion.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>)<span class="op">;</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Elevation profile</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>zion_transect_pnt.set_index(<span class="st">'dist'</span>)[<span class="st">'elev'</span>].plot(ax<span class="op">=</span>ax)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Distance (m)'</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Elevation (m)'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-zion-transect" class="cell quarto-layout-panel" data-execution_count="27">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 43.7%;justify-content: center;">
<div id="fig-zion-transect-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-zion-transect-output-1.png" class="img-fluid figure-img" data-ref-parent="fig-zion-transect" width="366"></p>
<figcaption class="figure-caption">(a) Raster and a line transect</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 56.3%;justify-content: center;">
<div id="fig-zion-transect-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-zion-transect-output-2.png" class="img-fluid figure-img" data-ref-parent="fig-zion-transect" width="472"></p>
<figcaption class="figure-caption">(b) Extracted elevation profile</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;5.4: Extracting a raster values profile to line</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="sec-extraction-to-polygons" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="sec-extraction-to-polygons"><span class="header-section-number">5.3.3</span> Extraction to polygons</h3>
<p>The final type of geographic vector object for raster extraction is polygons. Like lines, polygons tend to return many raster values per polygon. For continuous rasters (<a href="#fig-raster-extract-to-polygon">Figure&nbsp;<span>5.5</span></a> (a)), we typically want to generate summary statistics for raster values per polygon, for example to characterize a single region or to compare many regions. The generation of raster summary statistics, by polygons, is demonstrated in the code below using <code>rasterstats.zonal_stats</code>, which creates a list of summary statistics (in this case a list of length 1, since there is just one polygon).</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> rasterstats.zonal_stats(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    zion, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    src_srtm.read(<span class="dv">1</span>), </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    nodata <span class="op">=</span> src_srtm.nodata, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    affine <span class="op">=</span> src_srtm.transform, </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    stats <span class="op">=</span> [<span class="st">'mean'</span>, <span class="st">'min'</span>, <span class="st">'max'</span>]</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/usr/local/lib/python3.11/site-packages/rasterstats/main.py:156: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if 'Point' in geom.type:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>[{'min': 1122.0, 'max': 2661.0, 'mean': 1818.211830154405}]</code></pre>
</div>
</div>
<p>Transformation of the <code>list</code> to a <code>DataFrame</code> (e.g., to attach the derived attributes to the original polygon layer), is straightforward with the <code>pd.DataFrame</code> constructor.</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">max</th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1122.0</td>
<td>2661.0</td>
<td>1818.21183</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Because there is only one polygon in the example, a <code>DataFrame</code> with a single row is returned. However, if <code>zion</code> was composed of more than one polygon, we would accordingly get more rows in the <code>DataFrame</code>. The result provides useful summaries, for example that the maximum height in the park is around <code>2661</code> <span class="math inline">\(m\)</span> above see level.</p>
<p>Note the <code>stats</code> argument, where we determine what type of statistics are calculated per polygon. Possible values other than <code>'mean'</code>, <code>'min'</code>, <code>'max'</code> are:</p>
<ul>
<li><code>'count'</code>—The number of valid (i.e., excluding “No Data”) pixels</li>
<li><code>'nodata'</code>—The number of pixels with ’No Data”</li>
<li><code>'majority'</code>—The most frequently occurring value</li>
<li><code>'median'</code>—The median value</li>
</ul>
<p>See the <a href="https://pythonhosted.org/rasterstats/manual.html#statistics">documentation</a> of <code>rasterstats.zonal_stats</code> for the complete list. Additionally, the <code>rasterstats.zonal_stats</code> function accepts user-defined functions for calculating any custom statistics.</p>
<p>To count occurrences of categorical raster values within polygons (<a href="#fig-raster-extract-to-polygon">Figure&nbsp;<span>5.5</span></a> (b)), we can use masking (<a href="#sec-raster-cropping"><span>Section&nbsp;5.2</span></a>) combined with <code>np.unique</code>, as follows.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>out_image, out_transform <span class="op">=</span> rasterio.mask.mask(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    src_nlcd, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    zion.geometry.to_crs(src_nlcd.crs), </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    crop<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    nodata<span class="op">=</span><span class="dv">9999</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>counts <span class="op">=</span> np.unique(out_image, return_counts<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>(array([ 2,  3,  4,  5,  6,  7,  8, 15], dtype=uint8),
 array([  4205,  98285, 298299, 203701,    235,     62,    679, 852741]))</code></pre>
</div>
</div>
<p>According to the result, for example, pixel value <code>2</code> (“Developed” class) appears in <code>4205</code> pixels within the Zion polygon.</p>
<p><a href="#fig-raster-extract-to-polygon">Figure&nbsp;<span>5.5</span></a> illustrates the two types of raster extraction to polygons described above.</p>
<div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Continuous raster</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_srtm, ax<span class="op">=</span>ax)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>zion.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Categorical raster</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_nlcd, ax<span class="op">=</span>ax, cmap<span class="op">=</span><span class="st">'Set3'</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>zion.to_crs(src_nlcd.crs).plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-raster-extract-to-polygon" class="cell quarto-layout-panel" data-execution_count="31">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 49.2%;justify-content: center;">
<div id="fig-raster-extract-to-polygon-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-extract-to-polygon-output-1.png" class="img-fluid figure-img" data-ref-parent="fig-raster-extract-to-polygon" width="366"></p>
<figcaption class="figure-caption">(a) Continuous raster</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.8%;justify-content: center;">
<div id="fig-raster-extract-to-polygon-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-extract-to-polygon-output-2.png" class="img-fluid figure-img" data-ref-parent="fig-raster-extract-to-polygon" width="378"></p>
<figcaption class="figure-caption">(b) Categorical raster</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;5.5: Sample data used for continuous and categorical raster extraction to a polygon</figcaption><p></p>
</figure>
</div>
</div>
<!-- jn: what is the state of plotting categorical rasters? can it read the color palette from a file? -->
</section>
</section>
<section id="sec-rasterization" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-rasterization"><span class="header-section-number">5.4</span> Rasterization</h2>
<!-- jn: intro is missing -->
<section id="sec-rasterizing-points" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="sec-rasterizing-points"><span class="header-section-number">5.4.1</span> Rasterizing points</h3>
<p>Rasterization is the conversion of vector objects into their representation in raster objects. Usually, the output raster is used for quantitative analysis (e.g., analysis of terrain) or modeling. As we saw in <a href="01-spatial-data.html"><span>Chapter&nbsp;1</span></a>, the raster data model has some characteristics that make it conducive to certain methods. Furthermore, the process of rasterization can help simplify datasets because the resulting values all have the same spatial resolution: rasterization can be seen as a special type of geographic data aggregation.</p>
<p>The <strong>rasterio</strong> package contains the <a href="https://rasterio.readthedocs.io/en/stable/api/rasterio.features.html#rasterio.features.rasterize"><code>rasterio.features.rasterize</code></a> function for doing this work. To make it happen, we need to have the “template” grid definition, i.e., the “template” raster defining the extent, resolution and CRS of the output, in the <code>out_shape</code> (the output dimensions) and <code>transform</code> (the transformation matrix) arguments of <code>rasterio.features.rasterize</code>. In case we have an existing template raster, we simply need to query its <code>.shape</code> and <code>.transform</code>. On the other hand, if we need to create a custom template, e.g., covering the vector layer extent with specified resolution, there is some extra work to calculate both of these objects (see next example).</p>
<p>Furthermore, the <code>rasterio.features.rasterize</code> function requires the input vector shapes in the form of a generator of <code>(geom,value)</code> tuples, where:</p>
<ul>
<li><code>geom</code> is the given geometry (<strong>shapely</strong> geometry object)</li>
<li><code>value</code> is the value to be “burned” into pixels coinciding with the geometry (<code>int</code> or <code>float</code>)</li>
</ul>
<p>Again, this will be made clear in the next example.</p>
<p>The geographic resolution of the “template” raster has a major impact on the results: if it is too low (cell size is too large), the result may miss the full geographic variability of the vector data; if it is too high, computational times may be excessive. There are no simple rules to follow when deciding an appropriate geographic resolution, which is heavily dependent on the intended use of the results. Often the target resolution is imposed on the user, for example when the output of rasterization needs to be aligned to the existing raster.</p>
<p>To demonstrate rasterization in action, we will use a template raster that has the same extent and CRS as the input vector data <code>cycle_hire_osm_projected</code> (a dataset on cycle hire points in London, illustrated in <a href="#fig-rasterize-points">Figure&nbsp;<span>5.6</span></a> (a)) and a spatial resolution of 1000 <span class="math inline">\(m\)</span>. First, we take the vector layer and transform it to a projected CRS:</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>cycle_hire_osm_projected <span class="op">=</span> cycle_hire_osm.to_crs(<span class="dv">27700</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we need to calculate the <code>out_shape</code> and <code>transform</code> of our template raster. To calculate the transform, we combine the top-left corner of the <code>cycle_hire_osm_projected</code> bounding box with the required resolution (e.g., 1000 <span class="math inline">\(m\)</span>):</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>bounds <span class="op">=</span> cycle_hire_osm_projected.total_bounds</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>transform <span class="op">=</span> rasterio.transform.from_origin(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    west<span class="op">=</span>bounds[<span class="dv">0</span>], </span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    north<span class="op">=</span>bounds[<span class="dv">3</span>], </span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    xsize<span class="op">=</span>res, </span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    ysize<span class="op">=</span>res</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>transform</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>Affine(1000.0, 0.0, 523038.61452275474,
       0.0, -1000.0, 184971.40854297992)</code></pre>
</div>
</div>
<p>To calculate the <code>out_shape</code>, we divide the x-axis and y-axis extent by the resolution, and take the ceiling of the results:</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> math.ceil((bounds[<span class="dv">3</span>] <span class="op">-</span> bounds[<span class="dv">1</span>]) <span class="op">/</span> res)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> math.ceil((bounds[<span class="dv">2</span>] <span class="op">-</span> bounds[<span class="dv">0</span>]) <span class="op">/</span> res)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>shape <span class="op">=</span> (rows, cols)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>(11, 16)</code></pre>
</div>
</div>
<p>Now, we can rasterize. Rasterization is a very flexible operation: the results depend not only on the nature of the template raster, but also on the type of input vector (e.g., points, polygons), the pixel “activation” method, and the function applied when there is more than one match.</p>
<p>To illustrate this flexibility, we will try three different approaches to rasterization (<a href="#fig-rasterize-points">Figure&nbsp;<span>5.6</span></a> (b)-(d)). First, we create a raster representing the presence or absence of cycle hire points (known as presence/absence rasters). In this case, we transfer the value of <code>1</code> to all pixels where at least one point falls in. To transform the point <code>GeoDataFrame</code> into a generator of <code>shapely</code> geometries and the (fixed) values, we use the following expression. <!-- jn: maybe explain the code below in more detail? --> <!-- jn: also maybe use a different name than g? --></p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> ((g, <span class="dv">1</span>) <span class="cf">for</span> g <span class="kw">in</span> cycle_hire_osm_projected.geometry.to_list())</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>&lt;generator object &lt;genexpr&gt; at 0x7f62a9dbdcb0&gt;</code></pre>
</div>
</div>
<p>Then, the rasterizing expression takes the generator <code>g</code>, the template <code>shape</code> and <code>transform</code> as arguments.</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>ch_raster1 <span class="op">=</span> rasterio.features.rasterize(</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>    shapes<span class="op">=</span>g, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>shape, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>transform</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>ch_raster1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The result <code>ch_raster1</code> is an <code>ndarray</code> with the burned values of <code>1</code> where the pixel coincides with at least one point, and <code>0</code> in “unaffected” pixels.</p>
<p>To count the number of bike hire stations, we can use the fixed value of <code>1</code> combined with the <code>merge_alg=rasterio.enums.MergeAlg.add</code>, which means that multiple values burned into the same pixel are <em>summed</em>, rather than replaced keeping last (the default). <!--jn: rasterio.enums.MergeAlg.add definetely needs more explanation (maybe as a block)...--></p>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> ((g, <span class="dv">1</span>) <span class="cf">for</span> g <span class="kw">in</span> cycle_hire_osm_projected.geometry.to_list())</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>ch_raster2 <span class="op">=</span> rasterio.features.rasterize(</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    shapes<span class="op">=</span>g,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>shape,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>transform,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>    merge_alg<span class="op">=</span>rasterio.enums.MergeAlg.add</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>ch_raster2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The new output, <code>ch_raster2</code>, shows the number of cycle hire points in each grid cell. The cycle hire locations have different numbers of bicycles described by the capacity variable, raising the question, what is the capacity in each grid cell? To calculate that, we must sum the field (<code>'capacity'</code>) rather than the fixed values of <code>1</code>. This requires using an expanded generator of geometries and values, where we (1) extract both geometries and attribute values, and (2) filter out “No Data” values, which can be done as follows. <!-- jn: I think the code below should be explained in more detail... --></p>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> ((g, v) <span class="cf">for</span> g, v <span class="kw">in</span> cycle_hire_osm_projected[[<span class="st">'geometry'</span>, <span class="st">'capacity'</span>]] <span class="op">\</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>        .dropna(subset<span class="op">=</span><span class="st">'capacity'</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>        .to_numpy() <span class="op">\</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>        .tolist())</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>ch_raster3 <span class="op">=</span> rasterio.features.rasterize(</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    shapes<span class="op">=</span>g,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>shape,</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>transform,</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    merge_alg<span class="op">=</span>rasterio.enums.MergeAlg.add</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>ch_raster3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The result <code>ch_raster3</code> shows the total capacity of cycle hire points in each grid cell.</p>
<p>The input point layer <code>cycle_hire_osm_projected</code> and the three variants of rasterizing it <code>ch_raster1</code>, <code>ch_raster2</code>, and <code>ch_raster3</code> are shown in <a href="#fig-rasterize-points">Figure&nbsp;<span>5.6</span></a>.</p>
<div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Input points</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>cycle_hire_osm_projected.plot(column<span class="op">=</span><span class="st">'capacity'</span>, ax<span class="op">=</span>ax)<span class="op">;</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Presence/Absence</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(ch_raster1, transform<span class="op">=</span>transform, ax<span class="op">=</span>ax)<span class="op">;</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Point counts</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(ch_raster2, transform<span class="op">=</span>transform, ax<span class="op">=</span>ax)<span class="op">;</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Summed attribute values</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(ch_raster3, transform<span class="op">=</span>transform, ax<span class="op">=</span>ax)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-rasterize-points" class="cell quarto-layout-panel" data-execution_count="39">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.3%;justify-content: center;">
<div id="fig-rasterize-points-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-rasterize-points-output-1.png" class="img-fluid figure-img" data-ref-parent="fig-rasterize-points" width="458"></p>
<figcaption class="figure-caption">(a) Input points</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 49.7%;justify-content: center;">
<div id="fig-rasterize-points-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-rasterize-points-output-2.png" class="img-fluid figure-img" data-ref-parent="fig-rasterize-points" width="453"></p>
<figcaption class="figure-caption">(b) Presence/Absence</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-rasterize-points-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-rasterize-points-output-3.png" class="img-fluid figure-img" data-ref-parent="fig-rasterize-points" width="453"></p>
<figcaption class="figure-caption">(c) Point counts</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-rasterize-points-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-rasterize-points-output-4.png" class="img-fluid figure-img" data-ref-parent="fig-rasterize-points" width="453"></p>
<figcaption class="figure-caption">(d) Summed attribute values</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;5.6: Original data and three variants of point rasterization</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="rasterizing-lines-and-polygons" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="rasterizing-lines-and-polygons"><span class="header-section-number">5.4.2</span> Rasterizing lines and polygons</h3>
<p>Another dataset based on California’s polygons and borders (created below) illustrates rasterization of lines. There are three preliminary steps. First, we subset the California polygon.</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>california <span class="op">=</span> us_states[us_states[<span class="st">'NAME'</span>] <span class="op">==</span> <span class="st">'California'</span>]</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>california</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">GEOID</th>
<th data-quarto-table-cell-role="th">NAME</th>
<th data-quarto-table-cell-role="th">REGION</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">total_pop_10</th>
<th data-quarto-table-cell-role="th">total_pop_15</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>06</td>
<td>California</td>
<td>West</td>
<td>...</td>
<td>36637290.0</td>
<td>38421464.0</td>
<td>MULTIPOLYGON (((-118.60337 33.4...</td>
</tr>
</tbody>
</table>

<p>1 rows × 7 columns</p>
</div>
</div>
</div>
<p>Second, we “cast” the polygon into a <code>'MultiLineString'</code> geometry, using the <a href="https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.boundary.html"><code>.boundary</code></a> property that <code>GeoSeries</code> have.</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>california_borders <span class="op">=</span> california.geometry.boundary</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>california_borders</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>26    MULTILINESTRING ((-118.60337 33...
dtype: geometry</code></pre>
</div>
</div>
<p>Third, we create a template raster with a resolution of a <code>0.5</code> degree, using the same approach as in <a href="#sec-rasterizing-points"><span>Section&nbsp;5.4.1</span></a>.</p>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>bounds <span class="op">=</span> california_borders.total_bounds</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>transform <span class="op">=</span> rasterio.transform.from_origin(</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    west<span class="op">=</span>bounds[<span class="dv">0</span>], </span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    north<span class="op">=</span>bounds[<span class="dv">3</span>], </span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    xsize<span class="op">=</span>res, </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    ysize<span class="op">=</span>res</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> math.ceil((bounds[<span class="dv">3</span>] <span class="op">-</span> bounds[<span class="dv">1</span>]) <span class="op">/</span> res)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> math.ceil((bounds[<span class="dv">2</span>] <span class="op">-</span> bounds[<span class="dv">0</span>]) <span class="op">/</span> res)</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>shape <span class="op">=</span> (rows, cols)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>(19, 21)</code></pre>
</div>
</div>
<p>Finally, we rasterize <code>california_borders</code> based on the calculated template’s <code>shape</code> and <code>transform</code>. When considering line or polygon rasterization, one useful additional argument is <code>all_touched</code>. By default it is <code>False</code>, but when changed to <code>True</code>—all cells that are touched by a line or polygon border get a value. Line rasterization with <code>all_touched=True</code> is demonstrated in the code below (<a href="#fig-rasterize-lines-polygons">Figure&nbsp;<span>5.7</span></a>, left). We are also using <code>fill=np.nan</code> to set “background” values as “No Data”.</p>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>california_raster1 <span class="op">=</span> rasterio.features.rasterize(</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>    ((g, <span class="dv">1</span>) <span class="cf">for</span> g <span class="kw">in</span> california_borders.to_list()),</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>shape,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>transform,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>    all_touched<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>    fill<span class="op">=</span>np.nan</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare it to a polygon rasterization, with <code>all_touched=False</code> (the default), which selects only raster cells whose centroids are inside the selector polygon, as illustrated in <a href="#fig-rasterize-lines-polygons">Figure&nbsp;<span>5.7</span></a> (right).</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>california_raster2 <span class="op">=</span> rasterio.features.rasterize(</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>    ((g, <span class="dv">1</span>) <span class="cf">for</span> g <span class="kw">in</span> california.geometry.to_list()),</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>shape,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>transform,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    fill<span class="op">=</span>np.nan</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To illustrate which raster pixels are actually selected as part of rasterization, we also show them as points. This also requires the following code section to calculate the points, which we explain in <a href="#sec-spatial-vectorization"><span>Section&nbsp;5.5</span></a>.</p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> california_raster1.copy()</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> np.arange(<span class="dv">0</span>, california_raster1.size) <span class="op">\</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    .reshape(california_raster1.shape) <span class="op">\</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>    .astype(np.int32)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>shapes <span class="op">=</span> rasterio.features.shapes(ids, transform<span class="op">=</span>transform)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>pol <span class="op">=</span> <span class="bu">list</span>(shapes)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>pnt <span class="op">=</span> [shapely.geometry.shape(i[<span class="dv">0</span>]).centroid <span class="cf">for</span> i <span class="kw">in</span> pol]</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>pnt <span class="op">=</span> gpd.GeoSeries(pnt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-rasterize-lines-polygons">Figure&nbsp;<span>5.7</span></a> shows the input vector layer, the rasterization results, and the points <code>pnt</code>.</p>
<div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Line rasterization</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(california_raster1, transform<span class="op">=</span>transform, ax<span class="op">=</span>ax, cmap<span class="op">=</span><span class="st">'Set3'</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>gpd.GeoSeries(california_borders).plot(ax<span class="op">=</span>ax, edgecolor<span class="op">=</span><span class="st">'darkgrey'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>pnt.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'black'</span>, markersize<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Polygon rasterization</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(california_raster2, transform<span class="op">=</span>transform, ax<span class="op">=</span>ax, cmap<span class="op">=</span><span class="st">'Set3'</span>)</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>california.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'darkgrey'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>pnt.plot(ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'black'</span>, markersize<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-rasterize-lines-polygons" class="cell quarto-layout-panel" data-execution_count="46">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-rasterize-lines-polygons-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-rasterize-lines-polygons-output-1.png" class="img-fluid figure-img" data-ref-parent="fig-rasterize-lines-polygons" width="433"></p>
<figcaption class="figure-caption">(a) Line rasterization w/ <code>all_touched=True</code></figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-rasterize-lines-polygons-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-rasterize-lines-polygons-output-2.png" class="img-fluid figure-img" data-ref-parent="fig-rasterize-lines-polygons" width="433"></p>
<figcaption class="figure-caption">(b) Polygon rasterization w/ <code>all_touched=False</code></figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;5.7: Examples of line and polygon rasterization</figcaption><p></p>
</figure>
</div>
</div>
</section>
</section>
<section id="sec-spatial-vectorization" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-spatial-vectorization"><span class="header-section-number">5.5</span> Spatial vectorization</h2>
<p>Spatial vectorization is the counterpart of rasterization (<a href="#sec-rasterization"><span>Section&nbsp;5.4</span></a>). It involves converting spatially continuous raster data into spatially discrete vector data such as points, lines or polygons. There are three standard methods to convert a raster to a vector layer, which we cover next:</p>
<ul>
<li>Raster to polygons (<a href="#sec-raster-to-polygons"><span>Section&nbsp;5.5.1</span></a>)—the most straightforward form of vectorization, converting raster cells to polygons, where each pixel is represented by a rectangular polygon</li>
<li>Raster to points (<a href="#sec-raster-to-points"><span>Section&nbsp;5.5.2</span></a>)—has the additional step of calculating polygon centroids</li>
<li>Raster to contours (<a href="#sec-raster-to-contours"><span>Section&nbsp;5.5.3</span></a>)</li>
</ul>
<p>Let us demonstrate all three in the given order.</p>
<section id="sec-raster-to-polygons" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="sec-raster-to-polygons"><span class="header-section-number">5.5.1</span> Raster to polygons</h3>
<p>The <a href="https://rasterio.readthedocs.io/en/stable/api/rasterio.features.html#rasterio.features.shapes"><code>rasterio.features.shapes</code></a> function can be used to access to the raster pixel as polygon geometries, as well as raster values. The returned object is a generator, which yields <code>geometry,value</code> pairs. The additional <code>transform</code> argument is used to yield true spatial coordinates of the polygons, which is usually what we want. <!-- jn: the above paragraph is not easy to read, maybe rephrase? --></p>
<p>For example, the following expression returns a generator named <code>shapes</code>, referring to the pixel polygons.</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>shapes <span class="op">=</span> rasterio.features.shapes(</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>    rasterio.band(src_grain, <span class="dv">1</span>), </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>src_grain.transform</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>shapes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<pre><code>&lt;generator object shapes at 0x7f62aa0cece0&gt;</code></pre>
</div>
</div>
<p>We can generate all shapes at once into a <code>list</code> named <code>pol</code> with <code>list(shapes)</code>.</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>pol <span class="op">=</span> <span class="bu">list</span>(shapes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Each element in <code>pol</code> is a <code>tuple</code> of length 2, containing the GeoJSON-like <code>dict</code>—representing the polygon geometry and the value of the pixel(s)—which comprise the polygon. For example, check the first element of <code>pol</code> with <code>pol[0]</code>.</p>
<!-- jn: maybe the next sentence as a block -->
<p>Note that each raster cell is converted into a polygon consisting of five coordinates, all of which are stored in memory (explaining why rasters are often fast compared with vectors!).</p>
<p>To transform this <code>list</code> into a <code>GeoDataFrame</code>, we need few more steps of data reshaping. <!-- jn: add a sentence or two here... --></p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 'GeoSeries' with the polygons</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> [shapely.geometry.shape(i[<span class="dv">0</span>]) <span class="cf">for</span> i <span class="kw">in</span> pol]</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> gpd.GeoSeries(geom, crs<span class="op">=</span>src_grain.crs)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 'Series' with the values</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> [i[<span class="dv">1</span>] <span class="cf">for</span> i <span class="kw">in</span> pol]</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> pd.Series(values)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into a 'GeoDataFrame'</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> gpd.GeoDataFrame({<span class="st">'value'</span>: values, <span class="st">'geometry'</span>: geom})</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">value</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.0</td>
<td>POLYGON ((-1.50000 1.50000, -1....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.0</td>
<td>POLYGON ((-1.00000 1.50000, -1....</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.0</td>
<td>POLYGON ((-0.50000 1.50000, -0....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>2.0</td>
<td>POLYGON ((0.00000 -0.50000, 0.5...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">12</td>
<td>0.0</td>
<td>POLYGON ((0.50000 -1.00000, 0.5...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13</td>
<td>2.0</td>
<td>POLYGON ((1.00000 -1.00000, 1.0...</td>
</tr>
</tbody>
</table>

<p>14 rows × 2 columns</p>
</div>
</div>
</div>
<p>The resulting polygon layer is shown in <a href="#fig-raster-to-polygons">Figure&nbsp;<span>5.8</span></a>. As shown using the <code>edgecolor='black'</code> option, neighboring pixels sharing the same raster value are dissolved into larger polygons. The <code>rasterio.features.shapes</code> function does not offer a way to avoid this type of dissolving. One way to work around that is to convert an array with consecutive IDs, instead of the real values, to polygons, then extract the real values from the raster (see the example in <a href="#sec-raster-to-points"><span>Section&nbsp;5.5.2</span></a>).</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>result.plot(column<span class="op">=</span><span class="st">'value'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>, legend<span class="op">=</span><span class="va">True</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-raster-to-polygons" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-to-polygons-output-1.png" width="435" height="402" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.8: <code>grain.tif</code> converted to a polygon layer</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-raster-to-points" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="sec-raster-to-points"><span class="header-section-number">5.5.2</span> Raster to points</h3>
<p>To transform raster to points, we can use <code>rasterio.features.shapes</code>, same as in conversion to polygons (<a href="#sec-raster-to-points"><span>Section&nbsp;5.5.2</span></a>), only with the addition of the <code>.centroid</code> method to go from polygons to their centroids. However, to avoid dissolving nearby pixels, we will actually convert a raster with consecutive IDs, then extract the “true” values by point (it is not strictly necessary in this example, since the values of <code>elev.tif</code> are all unique).</p>
<p>First, we create an <code>ndarray</code> with consecutive IDs, matching the shape of <code>elev.tif</code> raster values.</p>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> src_elev.read(<span class="dv">1</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> r.copy()</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> np.arange(<span class="dv">0</span>, r.size).reshape(r.shape).astype(np.int32)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<pre><code>array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]], dtype=int32)</code></pre>
</div>
</div>
<p>Next, we use the <code>rasterio.features.shapes</code> function to create a point layer with the raster cell IDs.</p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>shapes <span class="op">=</span> rasterio.features.shapes(ids, transform<span class="op">=</span>src_elev.transform)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>pol <span class="op">=</span> <span class="bu">list</span>(shapes)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> [shapely.geometry.shape(i[<span class="dv">0</span>]).centroid <span class="cf">for</span> i <span class="kw">in</span> pol]</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> gpd.GeoSeries(geom, crs<span class="op">=</span>src_elev.crs)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> gpd.GeoDataFrame(geometry<span class="op">=</span>geom)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="52">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>POINT (-1.25000 1.25000)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>POINT (-0.75000 1.25000)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>POINT (-0.25000 1.25000)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">33</td>
<td>POINT (0.25000 -1.25000)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">34</td>
<td>POINT (0.75000 -1.25000)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">35</td>
<td>POINT (1.25000 -1.25000)</td>
</tr>
</tbody>
</table>

<p>36 rows × 1 columns</p>
</div>
</div>
</div>
<p>Finally, we extract (<a href="#sec-extraction-to-points"><span>Section&nbsp;5.3.1</span></a>) the <code>elev.tif</code> raster values to points, technically finalizing the raster-to-points conversion.</p>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>result[<span class="st">'value'</span>] <span class="op">=</span> rasterstats.point_query(</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>    result, </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    r, </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    nodata <span class="op">=</span> src_elev.nodata, </span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    affine <span class="op">=</span> src_elev.transform,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>    interpolate<span class="op">=</span><span class="st">'nearest'</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/usr/local/lib/python3.11/site-packages/rasterstats/io.py:313: UserWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn("Setting nodata to -999; specify nodata explicitly")</code></pre>
</div>
</div>
<p><a href="#fig-raster-to-points">Figure&nbsp;<span>5.9</span></a> shows the input raster and the resulting point layer.</p>
<div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Input raster</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>result.plot(column<span class="op">=</span><span class="st">'value'</span>, legend<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_elev, ax<span class="op">=</span>ax)<span class="op">;</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Points</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>result.plot(column<span class="op">=</span><span class="st">'value'</span>, legend<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax)</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_elev, cmap<span class="op">=</span><span class="st">'Greys'</span>, ax<span class="op">=</span>ax)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-raster-to-points" class="cell quarto-layout-panel" data-execution_count="54">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-raster-to-points-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-to-points-output-1.png" class="img-fluid figure-img" data-ref-parent="fig-raster-to-points" width="422"></p>
<figcaption class="figure-caption">(a) Input raster</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-raster-to-points-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-to-points-output-2.png" class="img-fluid figure-img" data-ref-parent="fig-raster-to-points" width="422"></p>
<figcaption class="figure-caption">(b) Points</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;5.9: Raster and point representation of <code>elev.tif</code></figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="sec-raster-to-contours" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="sec-raster-to-contours"><span class="header-section-number">5.5.3</span> Raster to contours</h3>
<p>Another common type of spatial vectorization is the creation of contour lines representing lines of continuous height or temperatures (<em>isotherms</em>), for example. We will use a real-world digital elevation model (DEM) because the artificial raster <code>elev.tif</code> produces parallel lines (task for the reader: verify this and explain why this happens). Plotting contour lines is straightforward, using the <code>contour=True</code> option of <code>rasterio.plot.show</code> (<a href="#fig-raster-contours1">Figure&nbsp;<span>5.10</span></a>).</p>
<div class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_dem, ax<span class="op">=</span>ax)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>    src_dem, </span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>ax, </span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    contour<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    levels<span class="op">=</span>np.arange(<span class="dv">0</span>,<span class="dv">1200</span>,<span class="dv">50</span>), </span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>    colors<span class="op">=</span><span class="st">'black'</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-raster-contours1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-contours1-output-1.png" width="451" height="424" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.10: Displaying raster contours</figcaption>
</figure>
</div>
</div>
</div>
<p>Unfortunately, <code>rasterio</code> does not provide any way of extracting the contour lines in the form of a vector layer, for uses other than plotting.</p>
<p>There are two possible workarounds:</p>
<ol type="1">
<li>Using <code>gdal_contour</code> on the <a href="https://gdal.org/programs/gdal_contour.html">command line</a> (see below), or through its Python interface <a href="https://gis.stackexchange.com/questions/360431/how-can-i-create-contours-from-geotiff-and-python-gdal-rasterio-etc-into-sh"><strong>osgeo</strong></a></li>
<li>Writing a custom function to export contour coordinates generated by, e.g., <a href="https://www.tutorialspoint.com/how-to-get-coordinates-from-the-contour-in-matplotlib"><strong>matplotlib</strong></a> or <a href="https://gis.stackexchange.com/questions/268331/how-can-i-extract-contours-from-a-raster-with-python"><strong>skimage</strong></a></li>
</ol>
<p>We demonstrate the first approach, using <code>gdal_contour</code>. Although we deviate from the Python-focused approach towards more direct interaction with GDAL, the benefit of <code>gdal_contour</code> is the proven algorithm, customized to spatial data, and with many relevant options. Both the <code>gdal_contour</code> program (along with other GDAL programs) and its <strong>osgeo</strong> Python wrapper, should already be installed on your system since GDAL is a dependency of <strong>rasterio</strong>. Using the command line pathway, generating 50 <span class="math inline">\(m\)</span> contours of the <code>dem.tif</code> file can be done as follows.</p>
<div class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>os.system(<span class="st">'gdal_contour -a elev data/dem.tif output/dem_contour.gpkg -i 50.0'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like all GDAL programs (also see <code>gdaldem</code> example in <a href="03-spatial-operations.html#sec-focal-operations"><span>Section&nbsp;3.3.4</span></a>), <code>gdal_contour</code> works with files. Here, the input is the <code>data/dem.tif</code> file and the result is exported to the <code>output/dem_contour.gpkg</code> file.</p>
<p>To illustrate the result, let’s read the resulting <code>dem_contour.gpkg</code> layer back into the Python environment. Note that the layer contains an attribute named <code>'elev'</code> (as specified using <code>-a elev</code>) with the contour elevation values.</p>
<div class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>contours1 <span class="op">=</span> gpd.read_file(<span class="st">'output/dem_contour.gpkg'</span>)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>contours1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="56">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">elev</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>750.0</td>
<td>LINESTRING (795382.355 8935384....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>800.0</td>
<td>LINESTRING (795237.703 8935384....</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2</td>
<td>650.0</td>
<td>LINESTRING (798098.379 8935384....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">29</td>
<td>29</td>
<td>450.0</td>
<td>LINESTRING (795324.083 8931774....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>30</td>
<td>450.0</td>
<td>LINESTRING (795488.616 8931774....</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">31</td>
<td>31</td>
<td>450.0</td>
<td>LINESTRING (795717.420 8931774....</td>
</tr>
</tbody>
</table>

<p>32 rows × 3 columns</p>
</div>
</div>
</div>
<p><a href="#fig-raster-contours2">Figure&nbsp;<span>5.11</span></a> shows the input raster and the resulting contour layer.</p>
<div class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(src_dem, ax<span class="op">=</span>ax)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>contours1.plot(ax<span class="op">=</span>ax, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-raster-contours2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-contours2-output-1.png" width="449" height="425" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.11: Contours of the <code>dem.tif</code> raster, calculated using the <code>gdal_contour</code> program</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-distance-to-nearest-geometry" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-distance-to-nearest-geometry"><span class="header-section-number">5.6</span> Distance to nearest geometry</h2>
<p>Calculating a raster of distances to the nearest geometry is an example of a “global” raster operation (<a href="03-spatial-operations.html#sec-global-operations-and-distances"><span>Section&nbsp;3.3.6</span></a>). To demonstrate it, suppose that we need to calculate a raster representing the distance to the nearest coast in New Zealand. This example also wraps many of the concepts introduced in this chapter and in previous chapter, such as raster aggregation (<a href="04-geometry-operations.html#sec-raster-agg-disagg"><span>Section&nbsp;4.3.3</span></a>), raster conversion to points (<a href="#sec-raster-to-points"><span>Section&nbsp;5.5.2</span></a>), and rasterizing points (<a href="#sec-rasterizing-points"><span>Section&nbsp;5.4.1</span></a>).</p>
<p>For the coastline, we will dissolve the New Zealand administrative division polygon layer and “extract” the boundary as a <code>'MultiLineString'</code> geometry.</p>
<div class="cell" data-execution_count="59">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>coastline <span class="op">=</span> gpd.GeoSeries(nz.unary_union, crs<span class="op">=</span>nz.crs) <span class="op">\</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>    .to_crs(src_nz_elev.crs) <span class="op">\</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>    .boundary</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>coastline</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="58">
<pre><code>0    MULTILINESTRING ((1229997.901 4...
dtype: geometry</code></pre>
</div>
</div>
<p>For a “template” raster, we will aggregate the New Zealand DEM, in the <code>nz_elev.tif</code> file, to 5 times coarser resolution. The code section below follows the aggeregation example in <a href="04-geometry-operations.html#sec-raster-agg-disagg"><span>Section&nbsp;4.3.3</span></a>, then replaces the original (aggregated) values with unique IDs, which is a preliminary step when converting to points, as explained in <a href="#sec-raster-to-points"><span>Section&nbsp;5.5.2</span></a>. Finally, we also replace “erase” (i.e., replace with <code>np.nan</code>) IDs which were <code>np.nan</code> in the aggregated elevation raster, i.e., beyond the land area of New Zealand. <!-- jn: the last sentence could be rephrased... --></p>
<div class="cell" data-execution_count="60">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>factor <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading aggregated array</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> src_nz_elev.read(<span class="dv">1</span>,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>(</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">int</span>(src_nz_elev.height <span class="op">*</span> factor),</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">int</span>(src_nz_elev.width <span class="op">*</span> factor)</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>    resampling<span class="op">=</span>rasterio.enums.Resampling.average</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Updating the transform</span></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>new_transform <span class="op">=</span> src_nz_elev.transform <span class="op">*</span> src_nz_elev.transform.scale(</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>    (src_nz_elev.width <span class="op">/</span> r.shape[<span class="dv">1</span>]),</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>    (src_nz_elev.height <span class="op">/</span> r.shape[<span class="dv">0</span>])</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating unique IDs per cell</span></span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> r.copy()</span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> np.arange(<span class="dv">0</span>, r.size).reshape(r.shape).astype(np.float32)</span>
<span id="cb81-18"><a href="#cb81-18" aria-hidden="true" tabindex="-1"></a><span class="co"># "Erasing" irrelevant IDs</span></span>
<span id="cb81-19"><a href="#cb81-19" aria-hidden="true" tabindex="-1"></a>ids[np.isnan(r)] <span class="op">=</span> np.nan</span>
<span id="cb81-20"><a href="#cb81-20" aria-hidden="true" tabindex="-1"></a>ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="59">
<pre><code>array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)</code></pre>
</div>
</div>
<p>The result is an array named <code>ids</code> with the IDs, and the corresponding <code>new_transform</code>, as plotted in <a href="#fig-raster-distances1">Figure&nbsp;<span>5.12</span></a>.</p>
<div class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(ids, transform<span class="op">=</span>new_transform, ax<span class="op">=</span>ax)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>gpd.GeoSeries(coastline).plot(ax<span class="op">=</span>ax, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-raster-distances1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-distances1-output-1.png" width="334" height="442" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.12: Template with cell IDs to calculate distance to nearest geometry</figcaption>
</figure>
</div>
</div>
</div>
<p>To calculate distances, we must convert each pixel to a vector (point) geometry. For this purpose, we use the technique demonstrated in <a href="#sec-raster-to-points"><span>Section&nbsp;5.5.2</span></a>.</p>
<div class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>shapes <span class="op">=</span> rasterio.features.shapes(ids, transform<span class="op">=</span>new_transform)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>pol <span class="op">=</span> <span class="bu">list</span>(shapes)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>pnt <span class="op">=</span> [shapely.geometry.shape(i[<span class="dv">0</span>]).centroid <span class="cf">for</span> i <span class="kw">in</span> pol]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The result <code>pnt</code> is a <code>list</code> of <code>shapely</code> geometries, representing raster cell centroids (excluding <code>np.nan</code> pixels):</p>
<p>Now we can calculate the corresponding <code>list</code> of distances, using the <code>.distance</code> method from <strong>shapely</strong>:</p>
<div class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>distances <span class="op">=</span> [(i, i.distance(coastline)) <span class="cf">for</span> i <span class="kw">in</span> pnt]</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>distances[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="62">
<pre><code>(&lt;POINT (1572956.546 6189460.927)&gt;,
 0    826.752396
 dtype: float64)</code></pre>
</div>
</div>
<p>Finally, we rasterize (see <a href="#sec-rasterizing-points"><span>Section&nbsp;5.4.1</span></a>) the distances into our raster template.</p>
<div class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>image <span class="op">=</span> rasterio.features.rasterize(</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>    distances,</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>    out_shape<span class="op">=</span>ids.shape,</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span>np.float_,</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>new_transform,</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>    fill<span class="op">=</span>np.nan</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>image</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="63">
<pre><code>array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])</code></pre>
</div>
</div>
<!-- jn: there is a file path in the code output... can we remove it? -->
<p>The final result, a raster of distances to the nearest coastline, is shown in <a href="#fig-raster-distances2">Figure&nbsp;<span>5.13</span></a>.</p>
<div class="cell" data-execution_count="65">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>rasterio.plot.show(image, transform<span class="op">=</span>new_transform, ax<span class="op">=</span>ax)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>gpd.GeoSeries(coastline).plot(ax<span class="op">=</span>ax, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-raster-distances2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="05-raster-vector_files/figure-html/fig-raster-distances2-output-1.png" width="334" height="442" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;5.13: Distance to nearest coastline in New Zealand</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="exercises" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="exercises"><span class="header-section-number">5.7</span> Exercises</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-geometry-operations.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Geometry operations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-reproj.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reprojecting geographic data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>