<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An introductory resource for working with geographic data in Python">

<title>Geocomputation with Python - 7&nbsp; Geographic data I/O</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-mapping.html" rel="next">
<link href="./07-reproj.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-read-write-plot.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Geographic data I/O</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Geocomputation with Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/geocompx/geocompy/" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-spatial-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Geographic data in Python</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-attribute-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Attribute data operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-spatial-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Spatial data operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-geometry-operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Geometry operations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-raster-vector.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Raster-vector interactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-reproj.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reprojecting geographic data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-read-write-plot.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Geographic data I/O</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Making maps with Python</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
  <h2 class="anchored">Note: The book is under construction 🏗</h2>
  <ul>
    <li><a href="https://github.com/geocompr/py/issues" class="nav-link active" data-scroll-target="https\://github.com/geocompr/py/issues">Open an issue ❔</a></li>
    <li><a href="https://discord.gg/PMztXYgNxp" class="nav-link" data-scroll-target="https\://discord.gg/PMztXYgNxp">Chat on Discord 📣</a></li>
  </ul>
  <hr>
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites"><span class="header-section-number">7.1</span> Prerequisites</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">7.2</span> Introduction</a></li>
  <li><a href="#sec-retrieving-open-data" id="toc-sec-retrieving-open-data" class="nav-link" data-scroll-target="#sec-retrieving-open-data"><span class="header-section-number">7.3</span> Retrieving open data</a></li>
  <li><a href="#sec-geographic-data-packages" id="toc-sec-geographic-data-packages" class="nav-link" data-scroll-target="#sec-geographic-data-packages"><span class="header-section-number">7.4</span> Geographic data packages</a></li>
  <li><a href="#geographic-web-services" id="toc-geographic-web-services" class="nav-link" data-scroll-target="#geographic-web-services"><span class="header-section-number">7.5</span> Geographic web services</a></li>
  <li><a href="#sec-file-formats" id="toc-sec-file-formats" class="nav-link" data-scroll-target="#sec-file-formats"><span class="header-section-number">7.6</span> File formats</a></li>
  <li><a href="#sec-data-input" id="toc-sec-data-input" class="nav-link" data-scroll-target="#sec-data-input"><span class="header-section-number">7.7</span> Data input (I)</a>
  <ul>
  <li><a href="#vector-data" id="toc-vector-data" class="nav-link" data-scroll-target="#vector-data"><span class="header-section-number">7.7.1</span> Vector data</a></li>
  <li><a href="#raster-data" id="toc-raster-data" class="nav-link" data-scroll-target="#raster-data"><span class="header-section-number">7.7.2</span> Raster data</a></li>
  </ul></li>
  <li><a href="#sec-data-output" id="toc-sec-data-output" class="nav-link" data-scroll-target="#sec-data-output"><span class="header-section-number">7.8</span> Data output (O)</a>
  <ul>
  <li><a href="#vector-data-1" id="toc-vector-data-1" class="nav-link" data-scroll-target="#vector-data-1"><span class="header-section-number">7.8.1</span> Vector data</a></li>
  <li><a href="#sec-data-output-raster" id="toc-sec-data-output-raster" class="nav-link" data-scroll-target="#sec-data-output-raster"><span class="header-section-number">7.8.2</span> Raster data</a></li>
  </ul></li>
  <li><a href="#sec-visual-outputs" id="toc-sec-visual-outputs" class="nav-link" data-scroll-target="#sec-visual-outputs"><span class="header-section-number">7.9</span> Visual outputs</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">7.10</span> Exercises</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/geocompx/geocompy/edit/main/08-read-write-plot.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="read-write" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Geographic data I/O</span></span></h1>
</div>

<!--
-->


<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="prerequisites" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="prerequisites"><span class="header-section-number">7.1</span> Prerequisites</h2>
<p>Let’s import the required packages:</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> fiona</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> shapely</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="introduction"><span class="header-section-number">7.2</span> Introduction</h2>
<p>This chapter is about reading and writing geographic data. Geographic data import is essential for geocomputation: real-world applications are impossible without data. Data output is also vital, enabling others to use valuable new or improved datasets resulting from your work. Taken together, these processes of import/output can be referred to as data I/O.</p>
<p>Geographic data I/O is often done with few lines of code at the beginning and end of projects. It is often overlooked as a simple one step process. However, mistakes made at the outset of projects (e.g.&nbsp;using an out-of-date or in some way faulty dataset) can lead to large problems later down the line, so it is worth putting considerable time into identifying which datasets are available, where they can be found and how to retrieve them. These topics are covered in <a href="#sec-retrieving-open-data"><span>Section&nbsp;7.3</span></a>, which describes various geoportals, which collectively contain many terabytes of data, and how to use them. To further ease data access, a number of packages for downloading geographic data have been developed, as described in <a href="#sec-geographic-data-packages"><span>Section&nbsp;7.4</span></a>.</p>
<p>There are many geographic file formats, each of which has pros and cons, described in <a href="#sec-file-formats"><span>Section&nbsp;7.6</span></a>. The process of reading and writing files in formats efficiently is covered in Sections <a href="#sec-data-input"><span>Section&nbsp;7.7</span></a> and <a href="#sec-data-output"><span>Section&nbsp;7.8</span></a>, respectively. The final Section <a href="#sec-visual-outputs"><span>Section&nbsp;7.9</span></a> demonstrates methods for saving visual outputs (maps), in preparation for <a href="09-mapping.html"><span>Chapter&nbsp;8</span></a> on visualization.</p>
</section>
<section id="sec-retrieving-open-data" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-retrieving-open-data"><span class="header-section-number">7.3</span> Retrieving open data</h2>
</section>
<section id="sec-geographic-data-packages" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-geographic-data-packages"><span class="header-section-number">7.4</span> Geographic data packages</h2>
</section>
<section id="geographic-web-services" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="geographic-web-services"><span class="header-section-number">7.5</span> Geographic web services</h2>
</section>
<section id="sec-file-formats" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="sec-file-formats"><span class="header-section-number">7.6</span> File formats</h2>
<p>Geographic datasets are usually stored as files or in spatial databases. File formats can either store vector or raster data, while spatial databases such as <a href="https://postgis.net/">PostGIS</a> can store both. The large variety of file formats may seem bewildering, but there has been much consolidation and standardization since the beginnings of GIS software in the 1960s when the first widely distributed program (<a href="https://news.harvard.edu/gazette/story/2011/10/the-invention-of-gis/">SYMAP</a>) for spatial analysis was created at Harvard University <span class="citation" data-cites="coppock_history_1991">[@coppock_history_1991]</span>.</p>
<p>GDAL (which should be pronounced “goo-dal”, with the double “o” making a reference to object-orientation), the Geospatial Data Abstraction Library, has resolved many issues associated with incompatibility between geographic file formats since its release in 2000. GDAL provides a unified and high-performance interface for reading and writing of many raster and vector data formats. Many open and proprietary GIS programs, including GRASS, ArcGIS and QGIS, use GDAL behind their GUIs for doing the legwork of ingesting and spitting out geographic data in appropriate formats.</p>
<p>GDAL provides access to more than 200 vector and raster data formats. <a href="#tbl-file-formats">Table&nbsp;<span>7.1</span></a> presents some basic information about selected and often used spatial file formats.</p>
<div id="tbl-file-formats" class="anchored">
<table class="table">
<caption>Table&nbsp;7.1: Commonly used spatial data file formats</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 34%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Extension</th>
<th>Info</th>
<th>Type</th>
<th>Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ESRI Shapefile</td>
<td><code>.shp</code> (the main file)</td>
<td>Popular format consisting of at least three files. No support for: files &gt; 2GB;mixed types; names &gt; 10 chars; cols &gt; 255.</td>
<td>Vector</td>
<td>Partially open</td>
</tr>
<tr class="even">
<td>GeoJSON</td>
<td><code>.geojson</code></td>
<td>Extends the JSON exchange format by including a subset of the simple feature representation; mostly used for storing coordinates in longitude and latitude; it is extended by the TopoJSON format</td>
<td>Vector</td>
<td>Open</td>
</tr>
<tr class="odd">
<td>KML</td>
<td><code>.kml</code></td>
<td>XML-based format for spatial visualization, developed for use with Google Earth. Zipped KML file forms the KMZ format.</td>
<td>Vector</td>
<td>Open</td>
</tr>
<tr class="even">
<td>GPX</td>
<td><code>.gpx</code></td>
<td>XML schema created for exchange of GPS data.</td>
<td>Vector</td>
<td>Open</td>
</tr>
<tr class="odd">
<td>FlatGeobuf</td>
<td><code>.fgb</code></td>
<td>Single file format allowing for quick reading and writing of vector data. Has streaming capabilities.</td>
<td>Vector</td>
<td>Open</td>
</tr>
<tr class="even">
<td>GeoTIFF</td>
<td><code>.tif/.tiff</code></td>
<td>Popular raster format. A TIFF file containing additional spatial metadata.</td>
<td>Raster</td>
<td>Open</td>
</tr>
<tr class="odd">
<td>Arc ASCII</td>
<td><code>.asc</code></td>
<td>Text format where the first six lines represent the raster header, followed by the raster cell values arranged in rows and columns.</td>
<td>Raster</td>
<td>Open</td>
</tr>
<tr class="even">
<td>SQLite/SpatiaLite</td>
<td><code>.sqlite</code></td>
<td>Standalone relational database, SpatiaLite is the spatial extension of SQLite.</td>
<td>Vector and raster</td>
<td>Open</td>
</tr>
<tr class="odd">
<td>ESRI FileGDB</td>
<td><code>.gdb</code></td>
<td>Spatial and nonspatial objects created by ArcGIS. Allows: multiple feature classes; topology. Limited support from GDAL.</td>
<td>Vector and raster</td>
<td>Proprietary</td>
</tr>
<tr class="even">
<td>GeoPackage</td>
<td><code>.gpkg</code></td>
<td>Lightweight database container based on SQLite allowing an easy and platform-independent exchange of geodata</td>
<td>Vector and (very limited) raster</td>
<td>Open</td>
</tr>
</tbody>
</table>
</div>
<p>An important development ensuring the standardization and open-sourcing of file formats was the founding of the Open Geospatial Consortium (<a href="http://www.opengeospatial.org/">OGC</a>) in 1994. Beyond defining the simple features data model (see <a href="02-spatial-data.html#sec-simple-features"><span>Section&nbsp;1.2.4</span></a>), the OGC also coordinates the development of open standards, for example as used in file formats such as KML and GeoPackage. Open file formats of the kind endorsed by the OGC have several advantages over proprietary formats: the standards are published, ensure transparency and open up the possibility for users to further develop and adjust the file formats to their specific needs.</p>
<p>ESRI Shapefile is the most popular vector data exchange format; however, it is not an open format (though its specification is open). It was developed in the early 1990s and has a number of limitations. First of all, it is a multi-file format, which consists of at least three files. It only supports 255 columns, column names are restricted to ten characters and the file size limit is 2 GB. Furthermore, ESRI Shapefile does not support all possible geometry types, for example, it is unable to distinguish between a polygon and a multipolygon. Despite these limitations, a viable alternative had been missing for a long time. In the meantime, <a href="https://www.geopackage.org/">GeoPackage</a> emerged, and seems to be a more than suitable replacement candidate for ESRI Shapefile. GeoPackage is a format for exchanging geospatial information and an OGC standard. The GeoPackage standard describes the rules on how to store geospatial information in a tiny SQLite container. Hence, GeoPackage is a lightweight spatial database container, which allows the storage of vector and raster data but also of non-spatial data and extensions. Aside from GeoPackage, there are other geospatial data exchange formats worth checking out (<a href="#tbl-file-formats">Table&nbsp;<span>7.1</span></a>).</p>
<p>The GeoTIFF format seems to be the most prominent raster data format. It allows spatial information, such as the CRS definition and the transformation matrix (see <a href="02-spatial-data.html#sec-using-rasterio"><span>Section&nbsp;1.3.2</span></a>), to be embedded within a TIFF file. Similar to ESRI Shapefile, this format was firstly developed in the 1990s, but as an open format. Additionally, GeoTIFF is still being expanded and improved. One of the most significant recent addition to the GeoTIFF format is its variant called COG (Cloud Optimized GeoTIFF). Raster objects saved as COGs can be hosted on HTTP servers, so other people can read only parts of the file without downloading the whole file (see Sections 8.6.2 and 8.7.2…).</p>
<p>There is also a plethora of other spatial data formats that we do not explain in detail or mention in <a href="#tbl-file-formats">Table&nbsp;<span>7.1</span></a> due to the book limits. If you need to use other formats, we encourage you to read the GDAL documentation about <a href="https://gdal.org/drivers/vector/index.html">vector</a> and <a href="https://gdal.org/drivers/raster/index.html">raster</a> drivers. Additionally, some spatial data formats can store other data models (types) than vector or raster. It includes LAS and LAZ formats for storing lidar point clouds, and NetCDF and HDF for storing multidimensional arrays.</p>
<p>Finally, spatial data is also often stored using tabular (non-spatial) text formats, including CSV files or Excel spreadsheets. This can be convenient to share spatial datasets with people who, or software that, struggle with spatial data formats.</p>
</section>
<section id="sec-data-input" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="sec-data-input"><span class="header-section-number">7.7</span> Data input (I)</h2>
<p>Executing commands such as <code>geopandas.read_file</code> (the main function we use for loading vector data) or <code>rasterio.open</code>+<code>.read</code> (the main functions used for loading raster data) silently sets off a chain of events that reads data from files. Moreover, there are many Python packages containing a wide range of geographic data or providing simple access to different data sources. All of them load the data into the Python environment or, more precisely, assign objects to your workspace, stored in RAM and accessible within the Python session.</p>
<section id="vector-data" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="vector-data"><span class="header-section-number">7.7.1</span> Vector data</h3>
<p>Spatial vector data comes in a wide variety of file formats. Most popular representations such as <code>.shp</code>, <code>.geojson</code>, and <code>.gpkg</code> files can be imported and exported with <code>geopandas</code> functions <code>read_file</code> and <code>to_file</code> (covered in Section @ref(sec-data-output)), respectively.</p>
<p><code>geopandas</code> uses GDAL to read and write data, via <code>fiona</code> (the <a href="https://github.com/geopandas/geopandas/issues/2217">default</a>) or <code>pyogrio</code> packages (a recently developed alternative to <code>fiona</code>). After <code>fiona</code> is imported, the command <code>fiona.supported_drivers</code> can be used to list drivers available to GDAL, including whether they can (<code>r</code>), append (<code>a</code>), or write (<code>w</code>) data, or all three:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fiona.supported_drivers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>{'DXF': 'rw',
 'CSV': 'raw',
 'OpenFileGDB': 'raw',
 'ESRIJSON': 'r',
 'ESRI Shapefile': 'raw',
 'FlatGeobuf': 'raw',
 'GeoJSON': 'raw',
 'GeoJSONSeq': 'raw',
 'GPKG': 'raw',
 'GML': 'rw',
 'OGR_GMT': 'rw',
 'GPX': 'rw',
 'MapInfo File': 'raw',
 'DGN': 'raw',
 'S57': 'r',
 'SQLite': 'raw',
 'TopoJSON': 'r'}</code></pre>
</div>
</div>
<p>Other, less common, drivers can be <a href="https://geopandas.org/en/stable/docs/user_guide/io.html">“activated”</a> by manually supplementing <code>fiona.supported_drivers</code>. The first argument of the <code>geopandas</code> versatile data import function <code>gpd.read_file</code> is <code>filename</code>, which is typically a string, but can also be a file connection. The content of a string could vary between different drivers. In most cases, as with the ESRI Shapefile (<code>.shp</code>) or the GeoPackage format (<code>.gpkg</code>), the <code>filename</code> argument would be a path or a URL to an actual file, such as <code>geodata.gpkg</code>. The driver is automatically selected based on the file extension, as demonstrated for a <code>.gpkg</code> file below:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>world <span class="op">=</span> gpd.read_file(<span class="st">'data/world.gpkg'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>world</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iso_a2</th>
<th data-quarto-table-cell-role="th">name_long</th>
<th data-quarto-table-cell-role="th">continent</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">lifeExp</th>
<th data-quarto-table-cell-role="th">gdpPercap</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>FJ</td>
<td>Fiji</td>
<td>Oceania</td>
<td>...</td>
<td>69.960000</td>
<td>8222.253784</td>
<td>MULTIPOLYGON (((-180.00000 -16....</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>TZ</td>
<td>Tanzania</td>
<td>Africa</td>
<td>...</td>
<td>64.163000</td>
<td>2402.099404</td>
<td>MULTIPOLYGON (((33.90371 -0.950...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>EH</td>
<td>Western Sahara</td>
<td>Africa</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>MULTIPOLYGON (((-8.66559 27.656...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">174</td>
<td>XK</td>
<td>Kosovo</td>
<td>Europe</td>
<td>...</td>
<td>71.097561</td>
<td>8698.291559</td>
<td>MULTIPOLYGON (((20.59025 41.855...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">175</td>
<td>TT</td>
<td>Trinidad and Tobago</td>
<td>North America</td>
<td>...</td>
<td>70.426000</td>
<td>31181.821196</td>
<td>MULTIPOLYGON (((-61.68000 10.76...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">176</td>
<td>SS</td>
<td>South Sudan</td>
<td>Africa</td>
<td>...</td>
<td>55.817000</td>
<td>1935.879400</td>
<td>MULTIPOLYGON (((30.83385 3.5091...</td>
</tr>
</tbody>
</table>

<p>177 rows × 11 columns</p>
</div>
</div>
</div>
<p>For some drivers, such as a File Geodatabase (<code>OpenFileGDB</code>), <code>filename</code> could be provided as a folder name. GeoJSON string can also be read from a character string:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>gpd.read_file(<span class="st">'{"type":"Point","coordinates":[34.838848,31.296301]}'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>POINT (34.83885 31.29630)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Alternatively, the <code>gpd.read_postgis</code> function can be used to read a vector layer from a PostGIS database.</p>
<p>Some vector formats, such as GeoPackage, can store multiple data layers. By default, <code>gpd.read_file</code> automatically reads the first layer of the file specified in <code>filename</code>. However, using the <code>layer</code> argument you can specify any other layer.</p>
<p>The <code>gpd.read_file</code> function also allows for reading just parts of the file into RAM with two possible mechanisms. The first one is related to the <code>where</code> argument, which allows specifying what part of the data to read using an SQL <code>WHERE</code> expression. An example below extracts data for Tanzania only (Figure …). It is done by specifying that we want to get all rows for which <code>name_long</code> equals to <code>"Tanzania"</code>:</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tanzania <span class="op">=</span> gpd.read_file(<span class="st">'data/world.gpkg'</span>, where<span class="op">=</span><span class="st">'name_long="Tanzania"'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tanzania</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iso_a2</th>
<th data-quarto-table-cell-role="th">name_long</th>
<th data-quarto-table-cell-role="th">continent</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">lifeExp</th>
<th data-quarto-table-cell-role="th">gdpPercap</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>TZ</td>
<td>Tanzania</td>
<td>Africa</td>
<td>...</td>
<td>64.163</td>
<td>2402.099404</td>
<td>MULTIPOLYGON (((33.90371 -0.950...</td>
</tr>
</tbody>
</table>

<p>1 rows × 11 columns</p>
</div>
</div>
</div>
<p>If you do not know the names of the available columns, a good approach is to just read one row of the data using the <code>rows</code> argument, which can be used to read the first N rows, then use the <code>.columns</code> property to examine the column names:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>gpd.read_file(<span class="st">'data/world.gpkg'</span>, rows<span class="op">=</span><span class="dv">1</span>).columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>Index(['iso_a2', 'name_long', 'continent', 'region_un', 'subregion', 'type',
       'area_km2', 'pop', 'lifeExp', 'gdpPercap', 'geometry'],
      dtype='object')</code></pre>
</div>
</div>
<p>The second mechanism uses the <code>mask</code> argument to filter data based on intersection with an existing geometry. This argument expects a geometry (<code>GeoDataFrame</code>, <code>GeoSeries</code>, or <code>shapely</code>) representing the area where we want to extract the data. Let’s try it using a small example—we want to read polygons from our file that intersect with the buffer of 50,000 <span class="math inline">\(m\)</span> of Tanzania’s borders. To do it, we need to (a) transform the geometry to a projected CRS (such as EPSG:32736), (b) prepare our “filter” by creating the buffer (<a href="05-geometry-operations.html#sec-buffers"><span>Section&nbsp;4.3.3</span></a>), and (c) transform back to the original CRS to be used as a mask:</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>tanzania_buf <span class="op">=</span> tanzania.to_crs(<span class="dv">32736</span>).<span class="bu">buffer</span>(<span class="dv">50000</span>).to_crs(<span class="dv">4326</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>tanzania_buf.iloc[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<p><img src="08-read-write-plot_files/figure-html/cell-9-output-1.svg" class="img-fluid"></p>
</div>
</div>
<p>Now, we can apply this “filter” using the <code>mask</code> argument.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tanzania_neigh <span class="op">=</span> gpd.read_file(<span class="st">'data/world.gpkg'</span>, mask<span class="op">=</span>tanzania_buf)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>tanzania_neigh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iso_a2</th>
<th data-quarto-table-cell-role="th">name_long</th>
<th data-quarto-table-cell-role="th">continent</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">lifeExp</th>
<th data-quarto-table-cell-role="th">gdpPercap</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>MZ</td>
<td>Mozambique</td>
<td>Africa</td>
<td>...</td>
<td>57.099</td>
<td>1079.823866</td>
<td>MULTIPOLYGON (((34.55999 -11.52...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>ZM</td>
<td>Zambia</td>
<td>Africa</td>
<td>...</td>
<td>60.775</td>
<td>3632.503753</td>
<td>MULTIPOLYGON (((30.74001 -8.340...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>MW</td>
<td>Malawi</td>
<td>Africa</td>
<td>...</td>
<td>61.932</td>
<td>1090.367208</td>
<td>MULTIPOLYGON (((32.75938 -9.230...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>BI</td>
<td>Burundi</td>
<td>Africa</td>
<td>...</td>
<td>56.688</td>
<td>803.172837</td>
<td>MULTIPOLYGON (((30.46967 -2.413...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>UG</td>
<td>Uganda</td>
<td>Africa</td>
<td>...</td>
<td>59.224</td>
<td>1637.275081</td>
<td>MULTIPOLYGON (((33.90371 -0.950...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>RW</td>
<td>Rwanda</td>
<td>Africa</td>
<td>...</td>
<td>66.188</td>
<td>1629.868866</td>
<td>MULTIPOLYGON (((30.41910 -1.134...</td>
</tr>
</tbody>
</table>

<p>9 rows × 11 columns</p>
</div>
</div>
</div>
<p>Our result, shown in <a href="#fig-read-shp-query">Figure&nbsp;<span>7.1</span></a>, contains Tanzania and every country within its 50,000 <span class="math inline">\(m\)</span> buffer. Note that the last two expressions are used to add text labels with the <code>name_long</code> of each country, placed at the country centroid:</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(ncols<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>,<span class="dv">5</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tanzania.plot(ax<span class="op">=</span>axes[<span class="dv">0</span>], color<span class="op">=</span><span class="st">'lightgrey'</span>, edgecolor<span class="op">=</span><span class="st">'grey'</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>tanzania_neigh.plot(ax<span class="op">=</span>axes[<span class="dv">1</span>], color<span class="op">=</span><span class="st">'lightgrey'</span>, edgecolor<span class="op">=</span><span class="st">'grey'</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>tanzania_buf.plot(ax<span class="op">=</span>axes[<span class="dv">1</span>], color<span class="op">=</span><span class="st">'none'</span>, edgecolor<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'where'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'mask'</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>tanzania.<span class="bu">apply</span>(<span class="kw">lambda</span> x: axes[<span class="dv">0</span>].annotate(text<span class="op">=</span>x[<span class="st">'name_long'</span>], xy<span class="op">=</span>x.geometry.centroid.coords[<span class="dv">0</span>], ha<span class="op">=</span><span class="st">'center'</span>), axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>tanzania_neigh.<span class="bu">apply</span>(<span class="kw">lambda</span> x: axes[<span class="dv">1</span>].annotate(text<span class="op">=</span>x[<span class="st">'name_long'</span>], xy<span class="op">=</span>x.geometry.centroid.coords[<span class="dv">0</span>], ha<span class="op">=</span><span class="st">'center'</span>), axis<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-read-shp-query" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-read-write-plot_files/figure-html/fig-read-shp-query-output-1.png" width="726" height="394" class="figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;7.1: Reading a subset of the vector data using a <code>where</code> query (left) and a <code>mask</code> (right)</figcaption>
</figure>
</div>
</div>
</div>
<p>Often we need to read CSV files (or other tabular formats) which have x and y coordinate columns, and turn them into a <code>GeoDataFrame</code> with point geometries. To do that, we can import the file using <code>pandas</code> (e.g., <code>pd.read_csv</code> or <code>pd.read_excel</code>), then go from <code>DataFrame</code> to <code>GeoDataFrame</code> using the <code>gpd.points_from_xy</code> function, as shown earlier in the book (See <a href="02-spatial-data.html#sec-vector-layer-from-scratch"><span>Section&nbsp;1.2.6</span></a> and <a href="04-spatial-operations.html#sec-spatial-joining"><span>Section&nbsp;3.3.4</span></a>). For example, the table <code>cycle_hire_xy.csv</code>, where the coordinates are stored in the <code>X</code> and <code>Y</code> columns in EPSG:4326, can be imported, converted to a <code>GeoDataFrame</code>, and plotted, as follows:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>cycle_hire <span class="op">=</span> pd.read_csv(<span class="st">'data/cycle_hire_xy.csv'</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> gpd.points_from_xy(cycle_hire[<span class="st">'X'</span>], cycle_hire[<span class="st">'Y'</span>], crs<span class="op">=</span><span class="dv">4326</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>geom <span class="op">=</span> gpd.GeoSeries(geom)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>cycle_hire_xy <span class="op">=</span> gpd.GeoDataFrame(data<span class="op">=</span>cycle_hire, geometry<span class="op">=</span>geom)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>cycle_hire_xy.plot()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="08-read-write-plot_files/figure-html/cell-12-output-1.png" width="440" height="264"></p>
</div>
</div>
<p>Instead of columns describing ‘XY’ coordinates, a single column can also contain the geometry information. Well-known text (WKT), well-known binary (WKB), and the GeoJSON formats are examples of this. For instance, the <code>world_wkt.csv</code> file has a column named WKT representing polygons of the world’s countries. To import and convert it to a <code>GeoDataFrame</code>, we can apply the <code>shapely.wkt.loads</code> function (<a href="02-spatial-data.html#sec-geometries"><span>Section&nbsp;1.2.5</span></a>) on WKT strings, to convert them into <code>shapely</code> geometries:</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>world_wkt <span class="op">=</span> pd.read_csv(<span class="st">'data/world_wkt.csv'</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>world_wkt[<span class="st">'geometry'</span>] <span class="op">=</span> world_wkt[<span class="st">'WKT'</span>].<span class="bu">apply</span>(shapely.wkt.loads)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>world_wkt <span class="op">=</span> gpd.GeoDataFrame(world_wkt)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>world_wkt.plot()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="08-read-write-plot_files/figure-html/cell-13-output-1.png" width="429" height="221"></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Not all of the supported vector file formats store information about their coordinate reference system. In these situations, it is possible to add the missing information using the <code>.set_crs</code> function. Please refer also to <a href="07-reproj.html#sec-querying-and-setting-coordinate-systems"><span>Section&nbsp;6.4</span></a> for more information.</p>
</div>
</div>
<p>As a final example, we will show how <code>geopandas</code> also reads KML files. A KML file stores geographic information in XML format—a data format for the creation of web pages and the transfer of data in an application-independent way (Nolan and Lang 2014 …). Here, we access a KML file from the web. First, we need to “activate” the <code>KML</code> driver, which isn’t available by default (see above):</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fiona.supported_drivers[<span class="st">'KML'</span>] <span class="op">=</span> <span class="st">'r'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This file contains more than one layer. To list the available layers, we can use the <code>fiona.listlayers</code> function:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> <span class="st">'https://developers.google.com/kml/documentation/KML_Samples.kml'</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fiona.listlayers(u)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>['Placemarks',
 'Highlighted Icon',
 'Paths',
 'Google Campus',
 'Extruded Polygon',
 'Absolute and Relative']</code></pre>
</div>
</div>
<p>Finally, we can choose the first layer <code>Placemarks</code> and read it, using <code>gpd.read_file</code> with an additional <code>layer</code> argument:</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>placemarks <span class="op">=</span> gpd.read_file(u, layer<span class="op">=</span><span class="st">'Placemarks'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="raster-data" class="level3" data-number="7.7.2">
<h3 data-number="7.7.2" class="anchored" data-anchor-id="raster-data"><span class="header-section-number">7.7.2</span> Raster data</h3>
<p>Similar to vector data, raster data comes in many file formats with some of them supporting multilayer files. <code>rasterio.open</code> is used to create a file connection to a raster file, which can be subsequently used to read the metadata and/or the values, as shown previously (<a href="02-spatial-data.html#sec-using-rasterio"><span>Section&nbsp;1.3.2</span></a>). For example:</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>src <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'data/srtm.tif'</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>src</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>&lt;open DatasetReader name='data/srtm.tif' mode='r'&gt;</code></pre>
</div>
</div>
<p>All of the previous examples read spatial information from files stored on your hard drive. However, GDAL also allows reading data directly from online resources, such as HTTP/HTTPS/FTP web resources. The only thing we need to do is to add a <code>/vsicurl/</code> prefix before the path to the file. Let’s try it by connecting to the global monthly snow probability at 500 m resolution for the period 2000-2012 (T. Hengl 2021 add reference…). Snow probability for December is stored as a Cloud Optimized GeoTIFF (COG) file (see <a href="#sec-file-formats"><span>Section&nbsp;7.6</span></a>). To read an online file, we just need to provide its URL together with the <code>/vsicurl/</code> prefix:</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"/vsicurl/https://zenodo.org/record/5774954/files/clm_snow.prob_esacci.dec_p.90_500m_s0..0cm_2000..2012_v2.0.tif"</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>src <span class="op">=</span> rasterio.<span class="bu">open</span>(url)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>src</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>&lt;open DatasetReader name='/vsicurl/https://zenodo.org/record/5774954/files/clm_snow.prob_esacci.dec_p.90_500m_s0..0cm_2000..2012_v2.0.tif' mode='r'&gt;</code></pre>
</div>
</div>
<p>In the example above <code>rasterio.open</code> creates a connection to the file without obtaining any values, as we did for the local <code>srtm.tif</code> file. The values can read, into an <code>ndarray</code>, using the <code>.read</code> method of the file connection (<a href="02-spatial-data.html#sec-using-rasterio"><span>Section&nbsp;1.3.2</span></a>). This allows us also to just read a small portion of the data without downloading the entire file. This is very useful when working with large datasets hosted online from resource-constrained computing environments such as laptops.</p>
<p>Another option is to extract raster values at particular points, directly from the file connection, using the <code>.sample</code> method (see <a href="04-spatial-operations.html#sec-spatial-subsetting"><span>Section&nbsp;3.4.1</span></a>). For example, we can get the snow probability for December in Reykjavik (70%) by specifying its coordinates and applying <code>.sample</code>:</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> src.sample([(<span class="op">-</span><span class="fl">21.94</span>, <span class="fl">64.15</span>)])</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="bu">list</span>(values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>[array([70], dtype=uint8)]</code></pre>
</div>
</div>
<p>The example above efficiently extracts and downloads a single value instead of the entire GeoTIFF file, saving valuable resources. The <code>/vsicurl/</code> prefix <strong>also works for vector file formats</strong>, enabling you to import datasets from online storage with <code>geopandas</code> just by adding it before the vector file URL.</p>
<p>Importantly, <code>/vsicurl/</code> is not the only prefix provided by GDAL—many more exist, such as <code>/vsizip/</code> to read spatial files from ZIP archives without decompressing them beforehand or <code>/vsis3/</code> for on-the-fly reading files available in AWS S3 buckets. You can learn more about it at <a href="https://gdal.org/user/virtual_file_systems.html" class="uri">https://gdal.org/user/virtual_file_systems.html</a>.</p>
<p>(To add example of reading rectangular extent…)</p>
</section>
</section>
<section id="sec-data-output" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="sec-data-output"><span class="header-section-number">7.8</span> Data output (O)</h2>
<p>Writing geographic data allows you to convert from one format to another and to save newly created objects for permanent storage. Depending on the data type (vector or raster), object class (e.g., <code>GeoDataFrame</code>), and type and amount of stored information (e.g., object size, range of values), it is important to know how to store spatial files in the most efficient way. The next two sections will demonstrate how to do this.</p>
<section id="vector-data-1" class="level3" data-number="7.8.1">
<h3 data-number="7.8.1" class="anchored" data-anchor-id="vector-data-1"><span class="header-section-number">7.8.1</span> Vector data</h3>
<p>The counterpart of <code>gpd.read_file</code> is the <code>.to_file</code> method that a <code>GeoDataFrame</code> has. It allows you to write <code>GeoDataFrame</code> objects to a wide range of geographic vector file formats, including the most common, such as <code>.geojson</code>, <code>.shp</code> and <code>.gpkg</code>. Based on the file name, <code>.to_file</code> decides automatically which driver to use. The speed of the writing process depends also on the driver.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>world.to_file(<span class="st">'output/world.gpkg'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note: if you try to write to the same data source again, the function will overwrite the file:</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>world.to_file(<span class="st">'output/world.gpkg'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Instead of overwriting the file, we could add a new layer to the file with <code>mode='a'</code> (“append” mode, as opposed to the default <code>mode='w'</code> for “write” mode). Appending is supported by several spatial formats, including GeoPackage. For example:</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>world.to_file(<span class="st">'output/world_many_features.gpkg'</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>world.to_file(<span class="st">'output/world_many_features.gpkg'</span>, mode<span class="op">=</span><span class="st">'a'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, <code>world_many_features.gpkg</code> will contain a polygonal layer named <code>world</code> with two “copies” of each country (that is 177×2=354 features, whereas the <code>world</code> layer has 177 features).</p>
<p>Alternatively, you can create another, separate, layer, within the same file. The GeoPackage format also supports multiple layers within one file. For example:</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>world.to_file(<span class="st">'output/world_many_layers.gpkg'</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>world.to_file(<span class="st">'output/world_many_layers.gpkg'</span>, layer<span class="op">=</span><span class="st">'world2'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this case, <code>world_many_layers.gpkg</code> has two “layers”, <code>world_many_layers</code> (same as the file name, when <code>layer</code> is unspecified) and <code>world2</code>. Incidentally, the contents of the two layers is identical, but this doesn’t have to be so. Each layer from such a file can be imported separately, as in:</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>gpd.read_file(<span class="st">'output/world_many_layers.gpkg'</span>, layer<span class="op">=</span><span class="st">'world_many_layers'</span>).head(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iso_a2</th>
<th data-quarto-table-cell-role="th">name_long</th>
<th data-quarto-table-cell-role="th">continent</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">lifeExp</th>
<th data-quarto-table-cell-role="th">gdpPercap</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>FJ</td>
<td>Fiji</td>
<td>Oceania</td>
<td>...</td>
<td>69.96</td>
<td>8222.253784</td>
<td>MULTIPOLYGON (((-180.00000 -16....</td>
</tr>
</tbody>
</table>

<p>1 rows × 11 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>gpd.read_file(<span class="st">'output/world_many_layers.gpkg'</span>, layer<span class="op">=</span><span class="st">'world2'</span>).head(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iso_a2</th>
<th data-quarto-table-cell-role="th">name_long</th>
<th data-quarto-table-cell-role="th">continent</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">lifeExp</th>
<th data-quarto-table-cell-role="th">gdpPercap</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>FJ</td>
<td>Fiji</td>
<td>Oceania</td>
<td>...</td>
<td>69.96</td>
<td>8222.253784</td>
<td>MULTIPOLYGON (((-180.00000 -16....</td>
</tr>
</tbody>
</table>

<p>1 rows × 11 columns</p>
</div>
</div>
</div>
</section>
<section id="sec-data-output-raster" class="level3" data-number="7.8.2">
<h3 data-number="7.8.2" class="anchored" data-anchor-id="sec-data-output-raster"><span class="header-section-number">7.8.2</span> Raster data</h3>
<p>To write a raster file using <strong>rasterio</strong>, we need to pass a raster file path to <code>rasterio.open</code>, in writing (<code>'w'</code>) mode. This implies creating a new empty file (or overwriting an existing one). As opposed to read (<code>'r'</code>, the default) mode, the <code>rasterio.open</code> function needs quite a lot of information, in addition to the file path and mode:</p>
<ul>
<li>An array with the raster values</li>
<li>Metadata describing the raster format and spatial properties</li>
</ul>
<p>The metadata needs to specify the following properties:</p>
<ul>
<li><code>driver</code>—The file format (The recommendation is <code>'GTiff'</code> for GeoTIFF)</li>
<li><code>height</code>—Number of rows</li>
<li><code>width</code>—Number of columns</li>
<li><code>count</code>—Number of bands</li>
<li><code>nodata</code>—The value which represents “No Data”, if any</li>
<li><code>dtype</code>—The raster data type, one of <strong>numpy</strong> types (e.g., <code>np.int64</code>)</li>
<li><code>crs</code>—The CRS, using an EPSG code (e.g., <code>4326</code>)</li>
<li><code>transform</code>—The transform matrix</li>
<li><code>compress</code>—A compression method to apply, such as <code>'lzw'</code>. This is optional and most useful for large rasters. Note that, at the time of writing, this <a href="https://gis.stackexchange.com/questions/404738/why-does-rasterio-compression-reduces-image-size-with-single-band-but-not-with-m">doesn’t work well</a> for writing multiband rasters.</li>
</ul>
<p>Once the file connection with the right metadata is ready, we do the actual writing using the <code>.write</code> method of the file connection. If there are several bands we may execute the <code>.write</code> method several times, as in <code>.write(a,n)</code>, where <code>a</code> is the array with band values and <code>n</code> is the band index (starting from <code>1</code>, see below). When done, we close the file connection using the <code>.close</code> method. Some functions, such as <code>rasterio.warp.reproject</code> used for resampling and reprojecting, directly accept a file connection in <code>'w'</code> mode, thus handling the writing (of a resampled or reprojected raster) for us.</p>
<p>Most of the properties are either straightforward to choose, based on our aims, (e.g., <code>driver</code>, <code>crs</code>, <code>compress</code>, <code>nodata</code>), or directly derived from the array with the raster values itself (e.g., <code>height</code>, <code>width</code>, <code>count</code>, <code>dtype</code>). The most complicated property is the <code>transform</code>, which specifies the raster origin and resolution. The <code>transform</code> is typically either obtained from an existing raster (serving as a “template”), or created from scratch based on manually specified origin and resolution values (e.g., using <code>rasterio.transform.from_origin</code>), or calculate automatically (e.g., using <code>rasterio.warp.calculate_default_transform</code>).</p>
<p>Earlier in the book, we have already demonstrated the four most common scenarios of writing rasters:</p>
<ul>
<li>Creating from scratch (<a href="02-spatial-data.html#sec-raster-from-scratch"><span>Section&nbsp;1.3.3</span></a>)—We created and wrote two rasters from scratch by associating the <code>elev</code> and <code>grain</code> arrays with an arbitrary spatial extent. The custom arbitrary <code>transform</code> created using <code>rasterio.transform.from_origin</code>.</li>
<li>Aggregating (<a href="05-geometry-operations.html#sec-raster-agg-disagg"><span>Section&nbsp;4.4.3</span></a>)—We wrote an aggregated a raster, by reading a resampled array from an exising raster, then updating the <code>transform</code> using <code>.transform.scale</code>.</li>
<li>Resampling (<a href="05-geometry-operations.html#sec-raster-resampling"><span>Section&nbsp;4.4.4</span></a>)—We resampled a raster into a custom grid, manually creating the <code>transform</code> using <code>rasterio.transform.from_origin</code>, then resampling and writing the output using <code>rasterio.warp.reproject</code>.</li>
<li>Reprojecting (<a href="07-reproj.html#sec-reprojecting-raster-geometries"><span>Section&nbsp;6.9</span></a>)—We reprojected a raster into another CRS, by automatically calculating an optimal <code>transform</code> using <code>rasterio.warp.calculate_default_transform</code>, then resampling and writing the output using <code>rasterio.warp.reproject</code>.</li>
</ul>
<p>A miminal example of writing a raster file named <code>r.tif</code> from scratch (i.e., the 1<sup>st</sup> scenario), to remind some of these concepts, is given below:</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># An array with raster values</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> np.array([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>]).reshape(<span class="dv">2</span>,<span class="dv">2</span>).astype(np.int8)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>array([[1, 2],
       [3, 4]], dtype=int8)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the transform</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>new_transform <span class="op">=</span> rasterio.transform.from_origin(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    west<span class="op">=-</span><span class="fl">0.5</span>, </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    north<span class="op">=</span><span class="fl">51.5</span>, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    xsize<span class="op">=</span><span class="dv">2</span>, </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    ysize<span class="op">=</span><span class="dv">2</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>new_transform</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>Affine(2.0, 0.0, -0.5,
       0.0, -2.0, 51.5)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the file connection with the metadata</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>dst <span class="op">=</span> rasterio.<span class="bu">open</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'output/r.tif'</span>, <span class="st">'w'</span>, </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    driver <span class="op">=</span> <span class="st">'GTiff'</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> r.shape[<span class="dv">0</span>],</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    width <span class="op">=</span> r.shape[<span class="dv">1</span>],</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    count <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    dtype <span class="op">=</span> r.dtype,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    crs <span class="op">=</span> <span class="dv">4326</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    transform <span class="op">=</span> new_transform</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>dst</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>&lt;open DatasetWriter name='output/r.tif' mode='w'&gt;</code></pre>
</div>
</div>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Writing the array values into the file</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>dst.write(r, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Closing the file</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dst.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code section creates a new file <code>output/r.tif</code>, which is a <span class="math inline">\(2 \times 2\)</span> raster, having a 2 decimal degree resolution, with the top-left corner placed over London.</p>
<p>To summarize, the various scenarios differ in two aspects:</p>
<ul>
<li>The way that the <code>transform</code> for the output raster is obtained:
<ul>
<li>Imported from an existing raster (see below)</li>
<li>Created from scratch, using <code>rasterio.transform.from_origin</code> (<a href="02-spatial-data.html#sec-raster-from-scratch"><span>Section&nbsp;1.3.3</span></a>)</li>
<li>Calculate automatically, using <code>rasterio.warp.calculate_default_transform</code> (<a href="07-reproj.html#sec-reprojecting-raster-geometries"><span>Section&nbsp;6.9</span></a>)</li>
</ul></li>
<li>The way that the raster is written:
<ul>
<li>Using the <code>.write</code> method, given an existing array (<a href="02-spatial-data.html#sec-raster-from-scratch"><span>Section&nbsp;1.3.3</span></a>, <a href="05-geometry-operations.html#sec-raster-agg-disagg"><span>Section&nbsp;4.4.3</span></a>)</li>
<li>Using <code>rasterio.warp.reproject</code> to calculate and write a resampled or reprojected array (<a href="05-geometry-operations.html#sec-raster-resampling"><span>Section&nbsp;4.4.4</span></a>, <a href="07-reproj.html#sec-reprojecting-raster-geometries"><span>Section&nbsp;6.9</span></a>)</li>
</ul></li>
</ul>
<p>To make the picture of raster export complete, there are three important concepts we haven’t covered yet: array and raster data types, writing multiband rasters, and handling “No Data” values.</p>
<p>Arrays (i.e., <code>ndarray</code> objects defined in package <strong>numpy</strong>) are used to store raster values when reading them from file, using <code>.read</code> (<a href="02-spatial-data.html#sec-using-rasterio"><span>Section&nbsp;1.3.2</span></a>). All values in an array are of the same type, whereas the <strong>numpy</strong> package supports numerous numeric data types of various precision (and, accordingly, memory footprint). Raster formats, such as GeoTIFF, support exactly the same data types, which means that reading a raster file uses as little RAM as possible. The most relevant types are summarized in <a href="#tbl-numpy-data-types">Table&nbsp;<span>7.2</span></a>.</p>
<div id="tbl-numpy-data-types" class="anchored">
<table class="table">
<caption>Table&nbsp;7.2: Numeric <code>numpy</code> data which are commonly used for rasters</caption>
<thead>
<tr class="header">
<th>Data type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>int8</code></td>
<td>Integer in a single byte (<code>-128</code> to <code>127</code>)</td>
</tr>
<tr class="even">
<td><code>int16</code></td>
<td>Integer in 16 bits (<code>-32768</code> to <code>32767</code>)</td>
</tr>
<tr class="odd">
<td><code>int32</code></td>
<td>Integer in 32 bits (<code>-2147483648</code> to <code>2147483647</code>)</td>
</tr>
<tr class="even">
<td><code>uint8</code></td>
<td>Unsigned integer (<code>0</code> to <code>255</code>)</td>
</tr>
<tr class="odd">
<td><code>uint16</code></td>
<td>Unsigned integer (<code>0</code> to <code>65535</code>)</td>
</tr>
<tr class="even">
<td><code>uint32</code></td>
<td>Unsigned integer (<code>0</code> to <code>4294967295</code>)</td>
</tr>
<tr class="odd">
<td><code>float16</code></td>
<td>Half-precision (16 bit) float (<code>-65504</code> to <code>65504</code>)</td>
</tr>
<tr class="even">
<td><code>float32</code></td>
<td>Single-precision (32 bit) float (<code>1e-38</code> to <code>1e38</code>)</td>
</tr>
<tr class="odd">
<td><code>float64</code></td>
<td>Double-precision (64 bit) float (<code>1e-308</code> to <code>1e308</code>)</td>
</tr>
</tbody>
</table>
</div>
<p>The raster data type can be specified when writing a raster (see above). For an existing raster file, the data type is accessible through the <code>.dtype</code> property of the metadata:</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>rasterio.<span class="bu">open</span>(<span class="st">'output/r.tif'</span>).meta[<span class="st">'dtype'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>'int8'</code></pre>
</div>
</div>
<p>The file <code>r.tif</code> has the data type <code>np.int8</code>, which we specified when creating it according to the data type of the original array:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>r.dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>dtype('int8')</code></pre>
</div>
</div>
<p>When reading the data back into the Python session, the array with the same data type is recreated:</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>rasterio.<span class="bu">open</span>(<span class="st">'output/r.tif'</span>).read().dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>dtype('int8')</code></pre>
</div>
</div>
<p>Writing multiband rasters is similar to writing single-band rasters, only that we need to:</p>
<ul>
<li>Define the number of layers (the <code>count</code> property in the metadata) that are going to be in the file we are creating</li>
<li>Execute the <code>.write</code> method multiple times, once for each layer</li>
</ul>
<p>For completeness, let’s demonstrate writing a multi-band raster named <code>r3.tif</code>, which is similar to <code>r.tif</code>, but having three bands with values <code>r</code>, <code>r*2</code>, and <code>r*3</code> (i.e., the array <code>r</code> multiplied by 1, 2, or 3). Since most of the metadata is going to be the same, this is also a good opportunity to (re-)demonstrate updating an existing metadata object rather than creating one from scratch.</p>
<p>First, let’s make a copy of the metadata we already have in <code>r.tif</code>:</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>dst_kwds <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/r.tif'</span>).meta.copy()</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>dst_kwds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>{'driver': 'GTiff',
 'dtype': 'int8',
 'nodata': None,
 'width': 2,
 'height': 2,
 'count': 1,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(2.0, 0.0, -0.5,
        0.0, -2.0, 51.5)}</code></pre>
</div>
</div>
<p>Second, we update the <code>count</code> entry, replacing <code>1</code> (single-band) with <code>3</code> (three-band):</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>dst_kwds.update(count<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>dst_kwds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>{'driver': 'GTiff',
 'dtype': 'int8',
 'nodata': None,
 'width': 2,
 'height': 2,
 'count': 3,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(2.0, 0.0, -0.5,
        0.0, -2.0, 51.5)}</code></pre>
</div>
</div>
<p>Finally, we can create a file connection using the updated metadata and then write the values of the three bands:</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>dst <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/r3.tif'</span>, <span class="st">'w'</span>, <span class="op">**</span>dst_kwds)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>dst.write(r,   <span class="dv">1</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>dst.write(r<span class="op">*</span><span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>dst.write(r<span class="op">*</span><span class="dv">3</span>, <span class="dv">3</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>dst.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As a result, a three-band raster named <code>r3.tif</code> is created.</p>
<p>Rasters often contain “No Data” values, representing missing data, e.g., unreliable measurement due to clouds or pixels outside of the photographed extent. In a <strong>numpy</strong> <code>ndarray</code> object, “No Data” values may be represented by the special <code>np.nan</code> value. However, due to computer memory limitations, only arrays of type <code>float</code> can contain <code>np.nan</code>, while arrays of type <code>int</code> cannot. For <code>int</code> rasters containing “No Data”, we typically mark missing data with a specific value beyond the valid range (e.g., <code>-9999</code>). The missing data “flag” is stored in the file (set through the <code>nodata</code> property of the file connection, see above). When reading an <code>int</code> raster with “No Data” back into Python, we need to be aware of these flags. Let’s demonstrate through examples.</p>
<p>We will start with the simpler case, rasters of type <code>float</code>. Since <code>float</code> arrays may contain the “native” value <code>np.nan</code>, representing “No Data” is straightforward. For example, suppose that we have a <code>float</code> array with <code>np.nan</code>:</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> np.array([<span class="fl">1.1</span>,<span class="fl">2.1</span>,np.nan,<span class="fl">4.1</span>]).reshape(<span class="dv">2</span>,<span class="dv">2</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>array([[1.1, 2.1],
       [nan, 4.1]])</code></pre>
</div>
</div>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>r.dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>dtype('float64')</code></pre>
</div>
</div>
<p>When writing the array to file, we do not need to specify any particular <code>nodata</code> value:</p>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>dst <span class="op">=</span> rasterio.<span class="bu">open</span>(</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'output/r_nodata_float.tif'</span>, <span class="st">'w'</span>, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    driver <span class="op">=</span> <span class="st">'GTiff'</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> r.shape[<span class="dv">0</span>],</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    width <span class="op">=</span> r.shape[<span class="dv">1</span>],</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    count <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    dtype <span class="op">=</span> r.dtype,</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>    crs <span class="op">=</span> <span class="dv">4326</span>,</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    transform <span class="op">=</span> new_transform</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>dst.write(r, <span class="dv">1</span>)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>dst.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is equivalent to <code>nodata=None</code>:</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>rasterio.<span class="bu">open</span>(<span class="st">'output/r_nodata_float.tif'</span>).meta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>{'driver': 'GTiff',
 'dtype': 'float64',
 'nodata': None,
 'width': 2,
 'height': 2,
 'count': 1,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(2.0, 0.0, -0.5,
        0.0, -2.0, 51.5)}</code></pre>
</div>
</div>
<p>Reading from the raster back into the Python session reproduces the same exact array, with <code>np.nan</code>:</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>rasterio.<span class="bu">open</span>(<span class="st">'output/r_nodata_float.tif'</span>).read()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<pre><code>array([[[1.1, 2.1],
        [nan, 4.1]]])</code></pre>
</div>
</div>
<p>Now, suppose that we have an <code>np.int32</code> array with missing data, which is inevitably flagged using a specific <code>int</code> value such as <code>-9999</code> (remember that we can’t store <code>np.nan</code> in an <code>int</code> array!):</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> np.array([<span class="dv">1</span>,<span class="dv">2</span>,<span class="op">-</span><span class="dv">9999</span>,<span class="dv">4</span>]).reshape(<span class="dv">2</span>,<span class="dv">2</span>).astype(np.int32)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>array([[    1,     2],
       [-9999,     4]], dtype=int32)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>r.dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>dtype('int32')</code></pre>
</div>
</div>
<p>When writing the array to file, we must specify <code>nodata=-9999</code> to keep track of our “No Data” flag:</p>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>dst <span class="op">=</span> rasterio.<span class="bu">open</span>(</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'output/r_nodata_int.tif'</span>, <span class="st">'w'</span>, </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    driver <span class="op">=</span> <span class="st">'GTiff'</span>,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> r.shape[<span class="dv">0</span>],</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    width <span class="op">=</span> r.shape[<span class="dv">1</span>],</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    count <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    dtype <span class="op">=</span> r.dtype,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>    nodata <span class="op">=</span> <span class="op">-</span><span class="dv">9999</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>    crs <span class="op">=</span> <span class="dv">4326</span>,</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>    transform <span class="op">=</span> new_transform</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>dst.write(r, <span class="dv">1</span>)</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>dst.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Examining the metadata confirms that the <code>nodata=-9999</code> setting was stored in the file <code>r_nodata_int.tif</code>.</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>rasterio.<span class="bu">open</span>(<span class="st">'output/r_nodata_int.tif'</span>).meta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>{'driver': 'GTiff',
 'dtype': 'int32',
 'nodata': -9999.0,
 'width': 2,
 'height': 2,
 'count': 1,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(2.0, 0.0, -0.5,
        0.0, -2.0, 51.5)}</code></pre>
</div>
</div>
<p>If you try to open the file in GIS software, such as QGIS, you will see the missing data interpreted (e.g., the pixel shown as blank), meaning that the software is aware of the flag. However, reading the data back into Python reproduces an <code>int</code> array with <code>-9999</code>, for the same reason stated before:</p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>src <span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'output/r_nodata_int.tif'</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> src.read()</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>array([[[    1,     2],
        [-9999,     4]]], dtype=int32)</code></pre>
</div>
</div>
<p>The Python user must thefore be mindful of “No Data” <code>int</code> rasters, for example to avoid interpreting the value <code>-9999</code> literally. For example, if we “forget” about the <code>nodata</code> flag, the literal calculation of the <code>.mean</code> would incorrectly include the value <code>-9999</code>:</p>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>r.mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>-2498.0</code></pre>
</div>
</div>
<p>There are two basic ways to deal with the situation:</p>
<ul>
<li>Converting the raster to <code>float</code></li>
<li>Using “No Data” masks</li>
</ul>
<p>First, particularly with small rasters where memory constraints are irrelevant, it may be more convenient to go from <code>int</code> to <code>float</code>, to gain the ability of the natural <code>np.nan</code> representation. Here is how we can do this with <code>r_nodata_int.tif</code>. We detect the missing data flag, conver the raster to <code>float</code>, and assign <code>np.nan</code> into the cells that are supposed to be missing:</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> r <span class="op">==</span> src.nodata</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> r.astype(np.float64)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>r[mask] <span class="op">=</span> np.nan</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<pre><code>array([[[ 1.,  2.],
        [nan,  4.]]])</code></pre>
</div>
</div>
<p>From there on, we deal with <code>np.nan</code> the usual way, such as using <code>np.nanmean</code> to calculate the mean excluding “No Data”:</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>np.nanmean(r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<pre><code>2.3333333333333335</code></pre>
</div>
</div>
<p>The second approach is to read the values into a so-called <a href="https://numpy.org/doc/stable/reference/maskedarray.generic.html#what-is-a-masked-array">“masked” array</a>, using the argument <code>masked=True</code>. A masked array can be thought of as an extended <code>ndarray</code>, with two components: <code>.data</code> (the values) and <code>.mask</code> (a corresponding boolean array marking “No Data” values):</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> src.read(masked<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<pre><code>masked_array(
  data=[[[1, 2],
         [--, 4]]],
  mask=[[[False, False],
         [ True, False]]],
  fill_value=-9999,
  dtype=int32)</code></pre>
</div>
</div>
<p>Using masked arrays is beyond the scope of this book. However, the basic idea is that many <strong>numpy</strong> operations “honor” the mask, so that the user does not have to keep track of the way that “No Data” values are marked, similarly to the natural <code>np.nan</code> representation. For example, the <code>.mean</code> of a masked array ignores the value <code>-9999</code>, because it is masked, taking into account just the valid values <code>1</code>, <code>2</code>, and <code>4</code>:</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>r.mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<pre><code>2.3333333333333335</code></pre>
</div>
</div>
<p>Keep in mind that, somewhat confusingly, <code>float</code> rasters may represent “No Data” using a specific value (such as <code>-9999.0</code>), instead, or in addition to (!), the native <code>np.nan</code> representation. In such cases, the same considerations shown for <code>int</code> apply to <code>float</code> rasters as well.</p>
</section>
</section>
<section id="sec-visual-outputs" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="sec-visual-outputs"><span class="header-section-number">7.9</span> Visual outputs</h2>
<p>…</p>
</section>
<section id="exercises" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="exercises"><span class="header-section-number">7.10</span> Exercises</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-reproj.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Reprojecting geographic data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-mapping.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Making maps with Python</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>