# ---
# description-meta: |
#   This book will teach you how to work with geographic data in Python.
#   It's a short and practical open source book in which you'll
#   develop and use geocomputation to solve practical
#   problems and lay the foundations for advanced geospatial applications.
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.14.4
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# ::: {.content-visible when-format="html"}
#
# ## Welcome {.unnumbered}
#
# This is the online home of *Geocomputation with Python*, a book on reproducible geographic data analysis with open source software.
#
# Inspired by the Free and Open Source Software for Geospatial ([FOSS4G](https://foss4g.org/)) movement this is an *open source book*.
# Find the code underlying the *geocompy* project on [GitHub](https://github.com/geocompx/geocompy), ensuring that the content is reproducible, transparent, and accessible.
# Making the book open source allows you or anyone else, to interact with the project by opening [issues](https://github.com/geocompx/geocompy/issues), making typo fixes and more, for the benefit of everyone.
#
# The book's website is built by GitHub Actions, which runs the code every time we make a change, ensuring code correctness and reproducibility.
# The current build status as follows:
#
# [![](https://github.com/geocompx/geocompy/actions/workflows/main.yaml/badge.svg)](https://github.com/geocompx/geocompy/actions/workflows/main.yaml)
#
# You can run the code in the book using GitHub CodeSpaces as follows (requires a GitHub account):
#
# [![](https://github.com/codespaces/badge.svg)](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863)
#
# For details on reproducing the book, see the README in the project's GitHub repo: <https://github.com/geocompx/geocompy>.
#
# <!-- 
# Note: we don't need this here but commenting out the content rather than deleting because some of it could be ported into the README.
# Reasonable? 
# Happy for these lines to be deleted also (RL 2022-12)
#
# ## Reproducing this book
#
# An important aspect of scientific research that results can be independently verified by others.
# Information that is generated by scientific means does not on auguments of authority or other [logical fallacies](https://bookofbadarguments.com/) as the basis for belief.
# Instead science relies on a network of people who are open minded yet skeptical to test assumptions and in some cases 'bust myths'.
#
# In the digital age, trust in claims depends on computational reproducibility.
#
# ### Local with Quarto
#
# To run the code locally, recommended for using the material on real data, you need to have a reasonable computer, e.g., with 8 GB RAM.
# You'll need administrative rights to install the requirements, which include:
#
# - A suitable integrated development environment (IDE) such as VS Code, RStudio or Jupyter Notebook
# - Quarto, if you want to reproduce the book's open access website
# - Either an Anaconda-like environment (we recommend `miniconda3`) or Docker to get systems dependencies
#
# See the [project's README](https://github.com/geocompx/geocompy) for details on getting set-up.
# After you have installed the necessary dependencies and cloned or [unzipped](https://github.com/geocompx/geocompy/archive/refs/heads/main.zip) the book's source code, you should be able to reproduce the code in its entirety with the following command:
#
# ```bash
# quarto preview
# ```
#
# If you see output like that below (with the IDE and browser arranged to see live updates after editing the source code), congratulations, it has worked!
#
# ![](https://user-images.githubusercontent.com/1825120/161321382-ac36aeab-5628-4bef-b3dd-7b2becdd4860.png)
#
# ### Local with Jupyter
#
# Alternatively, you can [download](https://github.com/geocompx/geocompy/archive/refs/heads/main.zip) and unzip the book's source code. The unzipped directory `py-main/code/chapters/` contains:
#
# * The source `ipynb` files, one for each chapter
# * The `data` sub-directory with the sample data used in the code sections
#
# Assuming that all required packages are installed (see beginning of each chapter), you can execute the `ipynb` files through your chosen working environment (VScode, Jupyter Notebook, etc.).  -->
#
# :::
#
